### ISSUE TITLE
Hosting this kind of website on github won't work

### ISSUE THREAD

**Issue by ghost** [Newawe/newawe#1]
We should try something like Gwiddle, x10, or something. Github sites cannot store data in databases.

**Comment by jeandrek** [comment]
They aren't hosting it on GH pages.

**Comment by robinp7720** [comment]
I would recommend we rename the gh-pages branch back to master.

**Comment by skistaddy** [comment]
Should we?

**Comment by skistaddy** [comment]
I'm gonna close it. We aren't hosting through GH pages.

**Comment by haylinmoore** [comment]
I don't see the issue with keeping it gh-pages

**Comment by skistaddy** [comment]
@herohamp Right now we are using GH pages for HTML, but we can't use it for PHP.

**Comment by robinp7720** [comment]
@bjskistad should I rename the branch to master? It allows us to create an actual gh-pages site for the project

**Comment by skistaddy** [comment]
@robinp7720 Sure.

**Comment by jeandrek** [comment]
@herohamp there isn't an issue, but there's no advantage either. (I prefer the name `master`.)
