### ISSUE TITLE
How should we communicate?

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#10]
Using the scratch forums is slow and laborious. We need a better and faster way of communicating. Does anyone have any ideas? I would suggest using Gitter.

**Comment by robinp7720** [comment]
https://gitter.im/bjskistad/newawe

**Comment by ghost** [comment]
I suggest making private developer forums on the website

**Comment by haylinmoore** [comment]
K I will setup a blab chatroom.

**Comment by robinp7720** [comment]
We have a gitter room. We don't need more forums and more chat rooms
