### ISSUE TITLE
How to test Newawe?

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#105]
Hey guys. I have made some changes to some newawe files on my computer. How can I test them though?

**Comment by bjskistad** [comment]
Localhost?

**Comment by HittmanA** [comment]
How do I set it up to use Node.js? I try installing nam and it says: 
    `Austins-MacBook-Air:~ austinhitt$ npm install
    npm WARN enoent ENOENT: no such file or directory, open '/Users/austinhitt/package.json'
    npm WARN austinhitt No description
    npm WARN austinhitt No repository field.
    npm WARN austinhitt No README data
    npm WARN austinhitt No license field.
    Austins-MacBook-Air:~ austinhitt$ 
`

**Comment by HittmanA** [comment]
Anyone?

**Comment by as-com** [comment]
You need to change to the directory in which you cloned the Newawe repository using `cd /path/to/newawe`

**Comment by HittmanA** [comment]
I can't seem to get nam to work so could someone test the patches for me?

**Comment by HittmanA** [comment]
Stupid autocorrect keeps making npm turn into nam

**Comment by Jonathan50** [comment]
> I can't seem to get npm to work so could someone test the patches for me?

What's the problem?

**Comment by bjskistad** [comment]
Did you install npm? `npm install npm`

**Comment by Jonathan50** [comment]
> Did you install npm? `npm install npm`

Use `npm install -g npm`

**Comment by bjskistad** [comment]
True, sometimes good to do both though.

**Comment by Jonathan50** [comment]
> True, sometimes good to do both though.

`npm install npm` will just install npm in the node_modules folder in your current directory. Probably not what you want.

**Comment by HittmanA** [comment]
thanks.

**Comment by HittmanA** [comment]
Yah it looks like it worked!
