### ISSUE TITLE
Code editor

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#108]
Hey guys! Would it be ok if I tried out a way for people to write and view the code?

**Comment by bjskistad** [comment]
http://newawelive.herohamp.xyz:8000/?p=create

**Comment by herohamp** [comment]
well could we use ace editor? then save the input data?

**Comment by HittmanA** [comment]
@bjskistad I know we already have an editor, but it does not display the results of the code.

**Comment by HittmanA** [comment]
@herohamp I had a different idea. Let me try it on localhost before I try it on newawe.

**Comment by herohamp** [comment]
ok tell me when so I can add to to live

**Comment by bjskistad** [comment]
ok

**Comment by HittmanA** [comment]
@herohamp Could you update the website now actually? I just added some stuff (not the editor yet)

**Comment by herohamp** [comment]
ok

**Comment by HittmanA** [comment]
Random question. How can I set a variable to the text in a text area (in javascript)?

**Comment by as-com** [comment]
`element.value`

If you're using Ace, use `editor.getValue`

**Comment by HittmanA** [comment]
Right now I'm using just pure javascript

**Comment by HittmanA** [comment]
and thanks btw

**Comment by HittmanA** [comment]
@as-com so say i have a text area with an id of Test and I want to set x to the text inside of it. I would use
`x = Test.value`
right?

**Comment by as-com** [comment]
You shouldn't be accessing elements through the global namespace - that's bad practice and I think not supported by all browsers. Instead, use `document.getElementById("Test").value`.

However, I doubt anyone would be willing to use a plain textarea to input code.

**Comment by HittmanA** [comment]
Why?

**Comment by HittmanA** [comment]
I will style the textarea to look nice.

**Comment by as-com** [comment]
Press tab. Need I say more?

**Comment by HittmanA** [comment]
Ugh true. Any idea how to fix that?

**Comment by HittmanA** [comment]
I have the bare (and I mean bare) bones of the code editor finished @as-com

**Comment by HittmanA** [comment]
@as-com @herohamp @bjskistad want to see the beginning of my code editor?

**Comment by bjskistad** [comment]
Yeah!

**Comment by HittmanA** [comment]
Ok Let me put it somewhere...

**Comment by HittmanA** [comment]
Ok @bjskistad ?

**Comment by bjskistad** [comment]
K.

**Comment by HittmanA** [comment]
Go to http://ahitt-industries.com/code.html and enter some html/javascript code (Proper code of course) into the text box then hit the button to set what your code does! PS try tab I made sure tab works!

**Comment by HittmanA** [comment]
Also tell me what you think!

**Comment by HittmanA** [comment]
Hey guys! I figured out how to make a live code editor where the code updates live as you type it!

**Comment by bjskistad** [comment]
Doesn't do anything for: 
`var awesome = 'awesome'
console.log('awesome')`

**Comment by HittmanA** [comment]
Sorry. I made an edit for the live coding that needs a fix. hang on a second.

**Comment by HittmanA** [comment]
ok @bjskistad ?

**Comment by HittmanA** [comment]
I fixed the editor. Now it works live and does javascript css and html! No php though.

**Comment by HittmanA** [comment]
Tell me any bugs or suggestions please!

**Comment by HittmanA** [comment]
Closing this. To many of my comments.
