### ISSUE TITLE
We need to sort out the plan with this repo.

### ISSUE THREAD

**Issue by Radical-from-Scratch** [Newawe/newawe#11]
I was told that the original repo would be the front-end stuff, but others are saying that it is being completely thrown away and that everyone should be here now.

What's the plan? We shouldn't let hard work go to waste.

**Comment by herohamp** [comment]
I don't see a need for the other repo. I do think we should just throw out the other repo and put all the work into this and and the api repo

**Comment by bjskistad** [comment]
I agree, we need to plan this out.

**Comment by Jonathan50** [comment]
The HTML of the old repo is copied here, so don't worry :smiley:

**Comment by bjskistad** [comment]
@Jonathan50 Yeah, but we need to plan out the rest of the website. It isn't all HTML, as you well know. :)

**Comment by Jonathan50** [comment]
I think the CSS is still on the old repo.

**Comment by Radical-from-Scratch** [comment]
But what about PHP and MySQL and whatnot?

**Comment by Jonathan50** [comment]
I think pretty much at the point we were with the old repo. (I'm not as familiar with the new repo as the old repo yet, so correct me if I'm wrong. I partly blame the messy code for that :package: )

**Comment by Icelys** [comment]
Basically. Next, we need to get the database interface working.

**Comment by bjskistad** [comment]
Yeah.

**Comment by bjskistad** [comment]
@Icelys Should I PM you credentials?

**Comment by Icelys** [comment]
Sure.

**Comment by bjskistad** [comment]
K. I'll do it on gitter.

**Comment by Radical-from-Scratch** [comment]
If you have the credentials, please send to me so I can set up forums/wiki.

**Comment by herohamp** [comment]
The CSS and JS Are Not On The Old Repo

**Comment by Radical-from-Scratch** [comment]
Okay But Why Do We Have To Talk Like This Now?
