### ISSUE TITLE
"Fourm"

### ISSUE THREAD

**Issue by Racer500** [Newawe/newawe#110]
The URL for the forums is https://newawe.gwiddle.co.uk/Fourm/, according to the homepage. You might want to fix that 😝

**Comment by herohamp** [comment]
Yeah that is just temp

**Comment by herohamp** [comment]
I will change it though when i get home

**Comment by HittmanA** [comment]
Hey @herohamp still need a bash script to auto update newawe?

**Comment by herohamp** [comment]
Yes! Yes! Please! I have been needing it!

**Comment by herohamp** [comment]
do you have one?

**Comment by HittmanA** [comment]
Yes I do!

**Comment by HittmanA** [comment]
Let me type it out. Bash script will follow in next comment:

**Comment by herohamp** [comment]
ok

**Comment by HittmanA** [comment]
You use a pi to host newawe right?

**Comment by herohamp** [comment]
yes. Will I need to install git for this bash script?

**Comment by HittmanA** [comment]
Yes it uses git

**Comment by HittmanA** [comment]
Ok install git

**Comment by HittmanA** [comment]
Then make a new file named clone.sh

**Comment by herohamp** [comment]
ok give me the script

**Comment by HittmanA** [comment]
make sure clone.sh is on the desktop

**Comment by HittmanA** [comment]
tell me when you got it

**Comment by herohamp** [comment]
done

**Comment by herohamp** [comment]
Ok I am in the file ready to edit!

**Comment by HittmanA** [comment]
Ok let me give you the bash script!

**Comment by HittmanA** [comment]
Here is the bash script:
`while true; do
rm -f -R /path/to/newawe/folder
cd /path/to/where/newawe/was/
git clone https://github.com/Newawe/newawe.git
echo "Newawe Installed!"
sleep (seconds you want it to wait)
done`

**Comment by HittmanA** [comment]
Wait a second

**Comment by herohamp** [comment]
ok. My issue is how do I stop newawe every x mins

**Comment by HittmanA** [comment]
Why does it need to stop?

**Comment by herohamp** [comment]
I could do all the other things just not stop newawe

**Comment by HittmanA** [comment]
Hmmmm. What happens if you don't stop newawe?

**Comment by herohamp** [comment]
because what if we change the server.js or config.json

**Comment by HittmanA** [comment]
So you need to stop the npm right?

**Comment by herohamp** [comment]
also what about usernames and passwords. is there a way to not delete them?

**Comment by herohamp** [comment]
yes I need to stop my node server.js proccess

**Comment by HittmanA** [comment]
Yes there is but it is time consuming to delete them all.

**Comment by HittmanA** [comment]
Cant you use 
`npm stop`
to stop the npm?

**Comment by herohamp** [comment]
So run newawe using npm start from now on?

**Comment by HittmanA** [comment]
I would think so.

**Comment by HittmanA** [comment]
Give me the directory tree for your pi. At least the newawe part.

**Comment by herohamp** [comment]
like all the way from root?

**Comment by HittmanA** [comment]
If that is ok with you. That way I can make the script custom so you don't have to edit anything, just copy and paste.

**Comment by herohamp** [comment]
/home/pi/Desktop/newawe-node/filename

**Comment by herohamp** [comment]
newawe-node holds all the files

**Comment by HittmanA** [comment]
Ok. Is there a subfolder that holds the usernames and passwords?

**Comment by herohamp** [comment]
nope just the data.json file

**Comment by HittmanA** [comment]
Thats fine.

**Comment by herohamp** [comment]
ok

**Comment by HittmanA** [comment]
give me some time to re-design the script.

**Comment by herohamp** [comment]
are we going to copy the data.json file to another location? then move it back?

**Comment by herohamp** [comment]
because that is my idea ATM

**Comment by HittmanA** [comment]
No just delete everything around it.

**Comment by herohamp** [comment]
ok but won't git remove it when we run the git command?

**Comment by HittmanA** [comment]
Wait your right. Yeah it'll be moved then moved back after deletion.

**Comment by HittmanA** [comment]
Ok let me go re-design the script.

**Comment by herohamp** [comment]
ok. that is what I was thinking we should do. It was so much eaiser when it was just php. Just overwrite all the files :P

**Comment by HittmanA** [comment]
Yeah

**Comment by herohamp** [comment]
Also I don't know if npm stop works

**Comment by herohamp** [comment]
I have an idea on stoping newawe!

**Comment by herohamp** [comment]
We need to do put
process.title = "newawe";

in the server.js then use 

killall -SIGINT newawe to kill it!

**Comment by HittmanA** [comment]
Ok yeah lets try that. I'll add that to my script.

**Comment by herohamp** [comment]
I talked in newawe chat and they said it was not the best idea 
https://gitter.im/bjskistad/newawe

**Comment by herohamp** [comment]
is it finished?

**Comment by HittmanA** [comment]
Why did they not say it was a good idea?

**Comment by Radical-from-Scratch** [comment]
The original issue has been solved, and so I am going to close it. All off-topic comments have been deleted.

**Comment by bjskistad** [comment]
So we have a new URL for the forums?

**Comment by Radical-from-Scratch** [comment]
Yep.
