### ISSUE TITLE
HOW TO ADD PNGs?

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#113]
How do I add the actual image to a .png file?

**Comment by as-com** [comment]
What are you trying to do?

**Comment by bjskistad** [comment]
I made a .png file and am trying to add the actual image. How do I do it?

**Comment by as-com** [comment]
Use the <img> tag?

**Comment by HittmanA** [comment]
Use `<img src="path/to/image.png"></img>`

**Comment by herohamp** [comment]
xD

**Comment by herohamp** [comment]
oh is your issue how our odd serveing works?

**Comment by Radical-from-Scratch** [comment]
"serveing" is not a word xP

**Comment by herohamp** [comment]
serving


there happy?

**Comment by Radical-from-Scratch** [comment]
It's just a joke :P

**Comment by herohamp** [comment]
I know :P

**Comment by bjskistad** [comment]
No, I made a .png file, how do I add the actual image to the file? Such as: https://github.com/Newawe/newawe/blob/master/pages/imgs/NewaweShareButton.png

**Comment by Radical-from-Scratch** [comment]
The reason nobody gave you a valid answer is we're having a hard time understanding the question---could you please rephrase it?

**Comment by bjskistad** [comment]
HOW DO I UPLOAD A PNG TO THE EDITOR?? (I'm not mad just to know. :P)

**Comment by herohamp** [comment]
What editor?

**Comment by bjskistad** [comment]
Any editor. A code editor.

**Comment by herohamp** [comment]
you don't

**Comment by herohamp** [comment]
you upload them to imgur or you localserver

**Comment by bjskistad** [comment]
Yes, you do.

**Comment by herohamp** [comment]
In what editor?

**Comment by bjskistad** [comment]
A code editor. Where you write code.

**Comment by herohamp** [comment]
ok. You use a <img> tag for html

**Comment by HittmanA** [comment]
@bjskistad Give me the image and I will host it for you. Then use `<img src="http://wherethefile.com/is.png"></img>`

**Comment by herohamp** [comment]
or use imgur

**Comment by HittmanA** [comment]
Ill host it for free with no nonsense and accounts and stuff.

**Comment by bjskistad** [comment]
I. Just. Want. To. Have. It. In. My. Editor.

**Comment by Radical-from-Scratch** [comment]
We could host it right on newawe.com

**Comment by HittmanA** [comment]
YOU CANT!!!!

**Comment by HittmanA** [comment]
YOU CANT HAVE IT IN THE EDITOR WITHOUT A TAG!!

**Comment by Radical-from-Scratch** [comment]
1) I can see why you're annoyed.
2) YES YOU CAN. BUT WHY DO WE HAVE TO TALK IN ALL CAPS?

**Comment by Jonathan50** [comment]
Let us stop spamming

**Comment by bjskistad** [comment]
2) I HAVE NO IDEA?!!!! XD

**Comment by herohamp** [comment]
I don't think he understands how editors work

**Comment by bjskistad** [comment]
I do.

**Comment by bjskistad** [comment]
Voila. https://github.com/Newawe/newawe/blob/master/pages/imgs/newaweimg.png A png file. How do I make one is what I'm wondering?

**Comment by herohamp** [comment]
ohhhhhhhhhhhhhh.

**Comment by herohamp** [comment]
What OS are you on? I can give you some software suggestions

**Comment by bjskistad** [comment]
I'm on chromebook os. c9.io is my editor

**Comment by herohamp** [comment]
oh well for an picture editor use https://pixlr.com/editor/

**Comment by herohamp** [comment]
Sorry about the confusion

**Comment by bjskistad** [comment]
NO WHAT I WANT! I want to make a .png file for the jel language and i want to add the logo to the docs.

**Comment by herohamp** [comment]
So do you have the image already?

**Comment by bjskistad** [comment]
Yeah, how do i put it in my editor?

**Comment by herohamp** [comment]
in the image editor?

**Comment by bjskistad** [comment]
No, https://c9.io , my code editor.

**Comment by bjskistad** [comment]
I want to add a local image file.

**Comment by herohamp** [comment]
upload it to your server that you are editing from

**Comment by bjskistad** [comment]
HOW???

**Comment by as-com** [comment]
If it's in the Git repo, just do git pull.

**Comment by bjskistad** [comment]
It isn't. How do I add it?

**Comment by as-com** [comment]
There should be an upload file function in Cloud9's IDE.

**Comment by bjskistad** [comment]
FOUND IT!!! YAY!!!!!! THANKS!!!!!!

**Comment by herohamp** [comment]
xD

**Comment by herohamp** [comment]
my email is done being spammed?

**Comment by bjskistad** [comment]
Yes. XD

**Comment by herohamp** [comment]
Add me to Jels github

**Comment by bjskistad** [comment]
I did.

**Comment by herohamp** [comment]
hmm try again

**Comment by bjskistad** [comment]
Check the org.

**Comment by bjskistad** [comment]
https://github.com/jel-lang
