### ISSUE TITLE
Should we use GET or DIRECTORIES for profiles

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe#116]
At the moment we have ?p=_page name_
But my question is this: Should we do 
?p=profile&u=_username_

Or..

?p=profile/_username_

Or...

/profile/_username_

If so, I only know how to do the first one, so some advice is appreciated.

Thanks.

**Comment by herohamp** [comment]
I think /profile/username because that is SEO ok

**Comment by joker314** [comment]
Ok, so how would one do that without creating the actual files (i.e. make them virtual)

**Comment by Radical-from-Scratch** [comment]
Umm....I only know how in PHP. Problem is, main site doesn't use PHP. I'll put the PHP explanation up just in case it's similar.

You need to create a .htaccess file at /profile, and then put this inside.

`RewriteEngine On`
`RewriteBase /`
`RewriteRule ^(.*)$ index.php`

This will make it so that all requests go to /profile/index.php. Even /profile/weurywieuyrwiefjw will go to /profile/index.php

**Comment by joker314** [comment]
And will the args get passed to index.php ?

**Comment by Radical-from-Scratch** [comment]
Are you talking about POST or GET or the stuff like ?variable=value

**Comment by joker314** [comment]
yeah

**Comment by Radical-from-Scratch** [comment]
No, which one?

**Comment by joker314** [comment]
POST would be good, but either. I want it to have:
/profiles/abc
to send index.php either ?file=abc or have the same but with post

**Comment by Radical-from-Scratch** [comment]
Lemme check if the POST arguments will, but I know the get ones will (just have the file find out its own web address)

**Comment by joker314** [comment]
Oh, I get it. So you could do $_SERVER['I forgot, but something like this']

Thanks, and I think everything travels through server.js, so we can handle it there # ?

**Comment by Radical-from-Scratch** [comment]
Yeah, but that's for PHP. I don't speak one word Node and can't help you there.

**Comment by joker314** [comment]
Okay.

**Comment by joker314** [comment]
Closing, and will ask a slightly different question in a new issue
