### ISSUE TITLE
Spelling error on the 404 page

### ISSUE THREAD

**Issue by BKFighter** [Newawe/newawe#118]
The 404 page says "Head hack to the home page" rather than "Head **back**..." which is a quick edit, and I'm not making a pull request for it...

https://github.com/Newawe/newawe/blob/master/pages/html/404.html

**Comment by RonSkons** [comment]
lol fixed

**Comment by Radical-from-Scratch** [comment]
You didn't need to make a whole new issue just for this.

**Comment by Jonathan50** [comment]
@Radical-from-Scratch There's no problem with that,
