### ISSUE TITLE
In-Activity

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#119]
Hey guys. Just wanted to say sorry for being so inactive.

**Comment by Radical-from-Scratch** [comment]
It's fine. Development is slower than usual. End-of-the-year stuff, I guess. I have the second-to-last week of June off, though.

**Comment by bjskistad** [comment]
I'm done with school.

**Comment by BKFighter** [comment]
@bjskistad Like just today or earlier. Today is my second day of summer vacation.

**Comment by bjskistad** [comment]
@BKFighter This is my third day.

**Comment by Firedrake969** [comment]
@Radical-from-Scratch you're still around?  :P

**Comment by bjskistad** [comment]
😆

**Comment by Dylan5797** [comment]
I have too much school stuff to keep up with web dev projects.

**Comment by Firedrake969** [comment]
@Radical-from-Scratch you're still around?  :P

**Comment by joker314** [comment]
Just want to greatly appologise too, I'll try and get back n track, it is just the amount of exams

**Comment by RonSkons** [comment]
Schools almost out for me. I'll be on a *lot* more over the summer.

**Comment by bjskistad** [comment]
Yay!

**Comment by Radical-from-Scratch** [comment]
School just got out yesterday.

**Comment by bjskistad** [comment]
Grats!

**Comment by bjskistad** [comment]
I'm going into 7th.

**Comment by RonSkons** [comment]
I'm almost done 7th

**Comment by RonSkons** [comment]
School goes on for so long here

**Comment by Jonathan50** [comment]
@RonSkons I have seen your new icon before

**Comment by Firedrake969** [comment]
why am I still subscribed to this

**Comment by RonSkons** [comment]
It is similar to [QuillzToxic](https://scratch.mit.edu/users/QuillzToxic/)'s icon. They are both made in FaceMyManga.com

**Comment by RonSkons** [comment]
I just realized how similar they look... Better Change it!

**Comment by bjskistad** [comment]
This is getting really off-topic and isn't really an issue, I'm gonna close.
