### ISSUE TITLE
package.json?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#12]
Should we have a JSON package?

**Comment by as-com** [comment]
Isn't package.json only for Node.js apps/libraries?

**Comment by jeandrek** [comment]
Do you mean an NPM package? Why?

**Comment by jeandrek** [comment]
@as-com 

> Isn't package.json only for Node.js apps/libraries?

I think other packages are allowed on NPM. Don't know how many PHP packages though.

**Comment by jeandrek** [comment]
https://www.npmjs.com/search?q=php

**Comment by skistaddy** [comment]
K, I was just wondering, everything I've made has had a package.json file. XD
