### ISSUE TITLE
Suggestion to move back to PHP

### ISSUE THREAD

**Issue by Radical-from-Scratch** [Newawe/newawe#124]
On Gitter, @herohamp said that development has slowed down since we moved to Node. He also pointed out that not many know Node and only know PHP. He suggested moving back to PHP, and I agree with this. What are everyone else's thoughts?

**Comment by HittmanA** [comment]
I totally agree. I do not understand node **at all** but understand php well enough!

**Comment by Radical-from-Scratch** [comment]
Locking conversation, this discussion is for developers only

**Comment by BKFighter** [comment]
I know neither really but I guess node is closer to js right? (Not that my opinion matters here since I won't likely be doing any of this).

**Comment by herohamp** [comment]
I agree

**Comment by RonSkons** [comment]
PHP ftw

**Comment by Jonathan50** [comment]
Noooo why?

**Comment by Jonathan50** [comment]
> Locking conversation, this discussion is for developers only

...

**Comment by BKFighter** [comment]
@Jonathan50 Because non-developers* aren't helping us, probably don't care, and don't really need a say.

_*Interpreting the term 'developers' to include anyone who is or was improving/designing/making/coding/programming/yGetTheIdea this website_

**Comment by Jonathan50** [comment]
Um what just happened

**Comment by Jonathan50** [comment]
Do most people here not know JavaScript?

**Comment by herohamp** [comment]
I belive we have switched to PHP our project loader is in php

**Comment by Jonathan50** [comment]
![](http://i.cubeupload.com/T5uxbE.png)

What? Noone mentioned me on this issue...

**Comment by herohamp** [comment]
Welcome

**Comment by Jonathan50** [comment]
> Welcome

What?

**Comment by BKFighter** [comment]
If you accepted the Gitter request you would have seen the conversation. (Not saying it's your fault that you haven't but you should because a lot goes on there).

**Comment by Jonathan50** [comment]
I have no idea what is happening. I got notified about this issue when nobody posted anything, GitHub thinks I was mentioned, @Radical-from-Scratch randomly locked the conversation, and @herohamp posted "Welcome"?

**Comment by BKFighter** [comment]
@Jonathan50 Then you're missing a lot. If you have time to read a few hundred messages (or at least the last ~50-100 (or just skim them)) here --> https://gitter.im/Newawe then you should be fairly up to date, but basically most people prefer php to node.

**Comment by Jonathan50** [comment]
> @Jonathan50 Then you're missing a lot. If you have time to read a few hundred messages (or at least the last ~50-100 (or just skim them)) here --> https://gitter.im/Newawe then you should be fairly up to date, but basically most people prefer php to node.

There are just 8 messages which have nothing to do with PHP or Node... Why do they prefer PHP to Node?

**Comment by BKFighter** [comment]
Ah, I see the problem. You got pushed to the public room. You need to go into the other room. Check your email for a message from gitter for... Nvm I'll just resend the invite to our private room.

**Comment by Radical-from-Scratch** [comment]
Jon doesn't use Gitter.

**Comment by Radical-from-Scratch** [comment]
Also, closing issue. The descision seems to be to use PHP

**Comment by BKFighter** [comment]
That explains a lot. Also, can't seem to resend the invite so.... ???

**Comment by scratchyone** [comment]
Why? How many people know JavaScript? Give a thumbs up response if you do

On Monday, June 20, 2016, Jordan B. <notifications@github.com> wrote:

> Also, closing issue. The descision seems to be to use PHP
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Newawe/newawe/issues/124#issuecomment-227312360>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AK8oJSpF4DdvZqE-rlUmymNtcOXLnwwCks5qNzZRgaJpZM4I59qP>
> .
>


--

**Comment by Jonathan50** [comment]
> Do most people here not know JavaScript?

> Why do they prefer PHP to Node?

**Comment by Jonathan50** [comment]
@Radical-from-Scratch Umm, why did you downvote @scratchyone's comment?

**Comment by Radical-from-Scratch** [comment]
Because I don't know Javascript.

**Comment by Jonathan50** [comment]
Oh.

**Comment by herohamp** [comment]
xD

**Comment by Radical-from-Scratch** [comment]
Jonathan50, please join the gitter chat: http://gitter.im/Newawe You won't miss these things that way

**Comment by Jonathan50** [comment]
Can't, sorry 😕 Is that a big problem?

**Comment by Jonathan50** [comment]
Why have we decided to move to PHP?

**Comment by herohamp** [comment]
YUPPPPPPPPPP

**Comment by herohamp** [comment]
because PHP is the best lang

**Comment by Jonathan50** [comment]
> because PHP is the best lang

Um... Why do you think that?

**Comment by Radical-from-Scratch** [comment]
because PHP *is* the best lang

**Comment by Jonathan50** [comment]
> because PHP is the best lang

Why do you think that?

**Comment by Mrcomputer1** [comment]
PHP :D
One of my fav langs (so is almost all the other langs know :P)

**Comment by Jonathan50** [comment]
Eh, if it makes most of the developers more productive, it's a mostly good thing.

**Comment by Mrcomputer1** [comment]
Shouldn't the "newawe" repo have issues enabled?

**Comment by bjskistad** [comment]
I'll enable it. :D

**Comment by Radical-from-Scratch** [comment]
You can enable and disable issues at will?
