### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by DrKat123** [Newawe/newawe#19]
Should we make more teams, like NodeJS developers, PHP, Ruby, Python, Other, etc?

**Comment by Jonathan50** [comment]
Please no first capital letter in tag names ;_;

**Comment by Jonathan50** [comment]
Newawe is written in Node.js.

**Comment by DrKat123** [comment]
Umm

The PHP team?

**Comment by Jonathan50** [comment]
There isn't any PHP...?

**Comment by bjskistad** [comment]
@Jonathan50 We need the PHP for forums and wiki.

**Comment by bjskistad** [comment]
I'm assuming. We're going to need PHP. Forums. Possibly wiki, if we have a wiki, and if we do, similar to Scratch's.

**Comment by herohamp** [comment]
I have been looking and can't find a Capitcha without using PHP

**Comment by bjskistad** [comment]
Yeah... I think we need to use reCAPTCHAS to find one without PHP

**Comment by robinp7720** [comment]
I kills me how people can't use google.
https://www.npmjs.com/package/recaptcha2

**Comment by bjskistad** [comment]
See, I knew only reCAPTCHAs use node.

**Comment by robinp7720** [comment]
reCAPATCHA is in my opionion, the only reliable capatcha system that isn't broken and looks decent

**Comment by bjskistad** [comment]
Okay.

**Comment by Radical-from-Scratch** [comment]
ReCaptcha all the way! We can experiment a little though.

**Comment by Jonathan50** [comment]
But we aren't *writing* any PHP.

**Comment by Radical-from-Scratch** [comment]
Yes we are! We need to hack with the forums to merge them with the main site.

**Comment by Jonathan50** [comment]
Okay.

**Comment by DrKat123** [comment]
See?

We're using PHP

**Comment by Radical-from-Scratch** [comment]
Are you talking to Jon or me?
