### ISSUE TITLE
Redesign?

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#20]
I kind of like githubs setup. I'm thinking this:
We have the Newawe icon where the gh icon is. And we add a serch bar where githubs is. Then, we have the rest of the tabs (Login, Create, etc.) after that, And then, we have the user's profile dropdown box.

**Comment by Icelys** [comment]
Possibly. We could do that.

**Comment by bjskistad** [comment]
Should we start? Or wait for one more person to agree?

**Comment by herohamp** [comment]
+1 I will do some work on it

**Comment by herohamp** [comment]
I just need sombody to fix the NodeJS CSS

**Comment by Radical-from-Scratch** [comment]
I'm ok with it. Let's do it.
