### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by haylinmoore** [Newawe/newawe#21]
What is the point of this repo? I though we were moving to nodeJS in the [NodeJS Repo](https://github.com/Newawe/newawe-node)? are we not? We already have register and login working. And by working I mean you can create an account then log in with it!

**Comment by robinp7720** [comment]
We have agreed on using meatier or feathers for this. The current backend used json files to store users. While this works, it is extremely slow and uses alot of ram. The entire json file must be loaded into ram before being able to access it.

Feathers and meatier makes it so we don't have to worry about authentication and user accounts.

**Comment by haylinmoore** [comment]
ok

**Comment by jeandrek** [comment]
There is a node repo? Cool. When it's ready, will you delete this repo and rename the node one to newawe?

**Comment by skistaddy** [comment]
@Jonathan50 Yes, we will.

**Comment by adri326** [comment]
Node.js is completely incompactible with PHP?

**Comment by skistaddy** [comment]
Pretty much. XD
