### ISSUE TITLE
We should make a new logo.

### ISSUE THREAD

**Issue by Radical-from-Scratch** [Newawe/newawe#22]
I am thinking something informative, what we do here, NOT bjskistad's personal logo, and something that looks all comp-sci like ( maybe some 0s and 1s in green). 

I was told DrKat123 is the team artist.

**Comment by bjskistad** [comment]
Yes, Kat is the artist.

**Comment by Radical-from-Scratch** [comment]
We are about 50% towards release, so moving to high-pri category.

**Comment by herohamp** [comment]
Well I would not say 50% as the page is broken ATM xD

**Comment by bjskistad** [comment]
Yeah. XD

**Comment by Radical-from-Scratch** [comment]
Fair enough.

**Comment by Radical-from-Scratch** [comment]
Hey, what happens if I put ALL of them?

**Comment by Radical-from-Scratch** [comment]
We should keep it at medium.

**Comment by bjskistad** [comment]
Yeah

**Comment by herohamp** [comment]
fine xD.

Come back next week for another episode of LABLE WARS!!!!!

**Comment by Radical-from-Scratch** [comment]
Label Wars Episode 2: Starring herohamp, bjskistad, and Radical-from-Scratch !

**Comment by Radical-from-Scratch** [comment]
You don't even need to be on Scratch to go off topic AT-er style

**Comment by herohamp** [comment]
Who will win?

**Comment by herohamp** [comment]
http://r78.cooltext.com/rendered/cooltext176107105278969.png

**Comment by bjskistad** [comment]
lol
[/offtopic]

**Comment by herohamp** [comment]
Ok lets get back on topic! Can sombody try to fix the CSS? Everything is broken!

**Comment by bjskistad** [comment]
Idk what's wrong with it. Maybe the path is wrong?

**Comment by herohamp** [comment]
I think so aswell.

**Comment by bjskistad** [comment]
Add a slash to the front? Is your live update still up?

**Comment by bjskistad** [comment]
I updated it. Should work.

**Comment by herohamp** [comment]
Hmm lets me try

**Comment by herohamp** [comment]
Nope your update does not work

**Comment by bjskistad** [comment]
Darn.

**Comment by herohamp** [comment]
Yes live is at http://newawelive.herohamp.xyz:8000/

**Comment by Radical-from-Scratch** [comment]
This isn't the CSS page.

**Comment by herohamp** [comment]
what do u mean?

**Comment by Radical-from-Scratch** [comment]
You are discussing CSS problems here. This is the LOGO issue.

**Comment by bjskistad** [comment]
Fine. I'll create a new issue.

**Comment by DrKat123** [comment]
Okay

**Comment by DrKat123** [comment]
What should i do? is there a specific color scheme? Or anything?

**Comment by herohamp** [comment]
our teal color and white, I think

**Comment by DrKat123** [comment]
Okay

**Comment by DrKat123** [comment]
I can make it tomorrow

maybe a specific idea on how will it look, for example: the old logo revamped, etc

**Comment by DrKat123** [comment]
I have a great idea in my head

**Comment by bjskistad** [comment]
@DrKat123 Awesome! Thanks!

**Comment by DrKat123** [comment]
okay. i'll post a sample of each ideas i have here
this might take a while

**Comment by DrKat123** [comment]
btw what image format will we use? svg? or png?

**Comment by DrKat123** [comment]
beta-logo:
![logo-beta](https://cloud.githubusercontent.com/assets/15071615/14577591/29b54546-03a0-11e6-90f4-bd0c3fdc8d92.png)

**Comment by DrKat123** [comment]
i don't rly like it myself :stuck_out_tongue:

**Comment by bjskistad** [comment]
Looks good!

**Comment by bjskistad** [comment]
btw we are using a .svg

**Comment by DrKat123** [comment]
okay
gonna redesign it as an svg...

**Comment by DrKat123** [comment]
okay
made a new logo (called favicon.svg)
we might also wanna delete favicon.png

**Comment by bjskistad** [comment]
Where is it?

**Comment by DrKat123** [comment]
pages/imgs/favicon.svg
