### ISSUE TITLE
CSS BROKE

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe#23]
So the css broke on newawe! I have tried to fix! and cannot! Live version is http://newawelive.herohamp.xyz:8000/

**Comment by Icelys** [comment]
Result of my few commits. I asked people to review the code, and the all said it was fine. 

:angry:

**Comment by herohamp** [comment]
Hmm can u fix it?

**Comment by Icelys** [comment]
The problem should be in global.html. Check it out. I'm on mobile, but I'll try to fix it soon if someone doesn't.

**Comment by herohamp** [comment]
I was looking in global and could not figure it out

**Comment by Jonathan50** [comment]
http://newawelive.herohamp.xyz:8000/

It's beautiful...

Isn't this fixed though? Should I close?

**Comment by Radical-from-Scratch** [comment]
Umm..l dunno. Let's not *close* but switch priority to low.

**Comment by bjskistad** [comment]
@Jonathan50 We're not using localhost anymore though. :(

**Comment by Jonathan50** [comment]
@bjskistad What do you mean by that...? Localhost is only accessible to you on your computer.

And if I download Newawe and run `npm run start` then it'll be accessible for me, and me only, on localhost.

**Comment by herohamp** [comment]
No it is still a major bug!!! We are using github as a CDN, we need to serve the files ourself.

**Comment by Jonathan50** [comment]
Open a new issue. And that's a problem, but not a bug.

**Comment by Icelys** [comment]
Moved to #38
