### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by adri326** [Newawe/newawe#25]
For those who PR here or who modify some files here, this repository isn't the actual repository. I am sorry for those who know a lot of PHP and who joined to ise these skills, but we're still using node.js, on a new repository: https://github.com/newawe/newawe-node

If you don't know node.js (like me), you should learn all the basics and install node.js in your computer so that you could debut anything.

**Comment by adri326** [comment]
Shall we modify the README.md?

**Comment by jeandrek** [comment]
Still using Node? Don't you mean are now using? :package:

**Comment by adri326** [comment]
Yeah, we're **now** using node, but I'm French, my English is not soo good

**Comment by ghost** [comment]
AFAIK, we _are_ using Node, but are not trashing this repository.

**Comment by haylinmoore** [comment]
Well what is the point of this repo! It just sits here and will be of no use!

**Comment by jeandrek** [comment]
@Radical-from-Scratch why would you think that?
@herohamp when the Node one is ready then will we delete this repo and rename newawe-node to newawe?

**Comment by skistaddy** [comment]
@Jonathan50 Yes.

**Comment by skistaddy** [comment]
Everyone think it's ready?

**Comment by ghost** [comment]
Ready to delete? Absolutely not! What if we change our mind? I mean that's like 99% not gonna happen, but there's no reason to delete it.

**Comment by skistaddy** [comment]
ok...

**Comment by jeandrek** [comment]
Um. We're pretty much passed the point we were with this repo on the new repo.

**Comment by ghost** [comment]
So? That doesn't mean we should delete it

**Comment by adri326** [comment]
@Radical-from-Scratch if you really want to save this repo, fork it, but having copies of the site won't help us, node and PHP are very different languages, while we update the node repo this one will be older and older and useless

**Comment by ghost** [comment]
I know we won't use it, but as far as I know, the decision was to keep it.
