### ISSUE TITLE
Repository description links to 404

### ISSUE THREAD

**Issue by towerofnix** [Newawe/newawe#26]
This is the GitHub repository description:

![link](https://cloud.githubusercontent.com/assets/9948030/14265864/60ffe9fc-fa9a-11e5-9a35-f0d3e528ef8b.png)

It links to [this](https://bjskistad.github.io/newawe):

![linked site](https://cloud.githubusercontent.com/assets/9948030/14265876/6cd7efc2-fa9a-11e5-9963-ce932546bb8d.png)

..a 404.

**Comment by skistaddy** [comment]
Sorry... We need to update the link... XD However, we're not running this repo anymore, so we don't have a website for it as far as I know.
