### ISSUE TITLE
Php not running on node.js server

### ISSUE THREAD

**Issue by Luckybanda** [Newawe/newawe#27]
I am unable to run php file on nodejs server.Please suggest some way to run php file on server made by using nodejs

**Comment by skistaddy** [comment]
I'm afraid I don't understand. This is our old repository, and it used to run on a PHP server I'm pretty sure. Feel free to check out our new repository!

**Comment by robinp7720** [comment]
PHP is an interprited language that requires an external webserver. Nodejs is a lanuage which is cabable of being a webserver.
