### ISSUE TITLE
New Logo! 

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#29]
Please remake the logo in [this project](https://scratch.mit.edu/projects/104840030/) to our new favicon.

**Comment by herohamp** [comment]
Ohh I love that thing. Give me some time to add

**Comment by bjskistad** [comment]
K.

**Comment by herohamp** [comment]
Let me just see if I can add it in.

**Comment by bjskistad** [comment]
K.

**Comment by herohamp** [comment]
Done check the website!
