### ISSUE TITLE
[array] doesn't work

### ISSUE THREAD

**Issue by adri326** [Newawe/newawe#3]
Replaced [] with array()

**Comment by skistaddy** [comment]
Is the issue fixed?

**Comment by skistaddy** [comment]
Wait, were you using PHP or JS? Cause in JS it's `var variable = [1, 2]` and in PHP `$variable = array(1, 2)`

**Comment by robinp7720** [comment]
@bjskistad [] can be used in PHP since 5.5 I believe. Personaly, [] is much more readable and should be recommended.

**Comment by skistaddy** [comment]
@robinp7720 True.
