### ISSUE TITLE
sign in

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe#34]
This is more of a question but is it possibel to log in using the keys like "010HwmIsrKGQ0Hk7hINXfzvy9ZPKTgMFN3FJlDgxeXTFZzMgq" BTW that was <h6>hi</h6>'s key

**Comment by Radical-from-Scratch** [comment]
Can you please reword what you are trying to say?

**Comment by herohamp** [comment]
Is it possible using the login keys that are sent to the log to login as somebody else?

**Comment by robinp7720** [comment]
Yes, they are called session tokens or session ID. It's how the webapp remembers who you are withouth sending your username and password everytime.

**Comment by Radical-from-Scratch** [comment]
Yep, robin's correct. However, since new keys are made every time, it is very unlikely two people have the same one.
