### ISSUE TITLE
Codacy

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#34]
Hey can someone allow the Codacy for Newawe to use web hooks to this repo please? It makes it much easier to fix bugs!

**Comment by skistaddy** [comment]
I think it's been enabled.

**Comment by HittmanA** [comment]
No it hasn't as far as I know.

**Comment by skistaddy** [comment]
How should I? Ask Hampton to. XD

**Comment by HittmanA** [comment]
XD

**Comment by skistaddy** [comment]
But seriously.

**Comment by HittmanA** [comment]
Lol ya

**Comment by CosmicWebServices** [comment]
bump

**Comment by skistaddy** [comment]
Wait, I got dis.

**Comment by skistaddy** [comment]
Nm, I don't got dis. 😆

**Comment by jeandrek** [comment]
It is working: https://www.codacy.com/app/Zeyphros/newawe
