### ISSUE TITLE
Please read, everyone.

### ISSUE THREAD

**Issue by ghost** [Newawe/newawe#35]
Unfortunately, bjskistad has decided to leave the project, because his parents want him to spend his time on other stuff. So from now on, herohamp is the main owner. This is kind of an unfortunate announcement, and it's very sad.

**Comment by ghost** [comment]
I've "assigned" you so you'll get a message.

**Comment by haylinmoore** [comment]
@Radical-from-Scratch is the co-owner

**Comment by HittmanA** [comment]
Thanks for the heads-up this is sad.

**Comment by RonSkons** [comment]
http://blog.newawe.com/wp-content/uploads/2016/06/Goodbye-@bjikstad-1.jpg

**Comment by skistaddy** [comment]
Everyone:
While this is sad and unfortunate, I am not abandoning it completely. My parents feel as if I'm not learning enough or working enough on this project. I will still be managing Newawe, but not working on it. I'm going to leave @herohamp, and his partner @Radical-from-Scratch to manage everything development-wise. I have loved working with you all, except for @Radical-from-Scratch (jk. :P), and hopefully will comeback when I have more knowledge. (In PHP, mostly.)

**Comment by herohamp** [comment]
and hopefully @Radical-from-Scratch does not wipe our blog again. JK

**Comment by haylinmoore** [comment]
@bjskistad why don't you join the dev team then? I have learned a lot about php just by looking at our code

**Comment by Firedrake969** [comment]
why PHP :P

**Comment by herohamp** [comment]
because!

**Comment by Jonathan50** [comment]
> why PHP :P

Read https://github.com/Newawe/newawe-node/issues/124

> because!

?

**Comment by Firedrake969** [comment]
"because" alone isn't a reason

**Comment by herohamp** [comment]
Rants about PHP are everywhere, and they even come from smart guys. When Jeff Atwood wrote yet another rant about PHP, it made me think about the good parts of PHP.

The biggest problem of these rants is that they come from people stuck in the old days of PHP. They either don't care or they don't want to admit that PHP actually evolves at a very fast pace, both at the language level but also at the community level. In fact, it evolves much faster than any other language or web platform. It has not always been the case, but the last 5 years have been an amazing journey for PHP.

Before talking about the amazing things the PHP community has achieved recently, let's have a look at some interesting numbers: PHP is used by 77.9% of all the websites whose server-side programming language is known. WordPress is used by 16.6% of all the websites in the world. If you have a look at the top three CMSes, for the websites that use a monitored content management system: Wordpress is first with 54.3%, Joomla is second with 9.2%, and Drupal is third with 6.8%. Three products written in PHP.

PHP must have done something right, no?

Now, let me tell you a secret, the PHP "tour de force": Despite the changes over the years, PHP is still the easiest language to learn for non-technical people: it allows anyone to create dynamic websites faster than with any other technologies, it allows anyone to host websites cheaply and without any hassles. PHP is probably not the best designed language in the world, but it lets you get things done, and you can't argue with that.

PHP, the Language
PHP 5.0 (released in 2004) brought us a very solid object model... wait a minute, I'm talking about something released almost 8 years ago. Fast forward now. The latest PHP release, PHP 5.4, comes with all the bells and whistles you might dream of in a modern web language: yes, PHP supports namespaces; yes, PHP supports closures; yes, PHP supports traits.

It took some time, but PHP 5.4 also comes with some nice syntactic sugar that makes the whole experience better than ever: yes, PHP supports [] to define arrays; yes, PHP supports calling a method on a newly created object ((new Foo())->bar()); yes, PHP supports getting an array item from any expression ($foo->bar()[1]).

PHP has even learned from its mistakes: register_globals and magic_quotes are definitely gone.

Last, but not the least, PHP even comes with a built-in web server that eases local testing... and it starts in a matter of micro-seconds.

Next challenges: How do we "upgrade" all the old tutorials talking about PHP on the web? What is the best way to support the WebSocket technology in a PHP application?

PHP, the Ecosystem
Having a good language is great, but having a great ecosystem is even better. And the PHP ecosystem has evolved a lot in the last few years.

Git
I won't talk too much about this one. Git is everywhere and PHP embraced Git pretty fast. Almost all major PHP libraries, frameworks, and products are now using Git, including PHP itself.

Composer
Two years ago, I wanted to get rid of my ugly-PEAR-hack I did in symfony 1 to support plugins. I wanted to replace it with something that was able to manage project dependencies, not a global installer like PEAR. Managing dependencies is not an easy task, so I tried to find the best algorithm to manage software dependencies; I had a look at everything: from Perl to Ruby, from Debian to Redhat. Nothing was satisfactory: only homegrown solutions that happen to work... empirically. Then, I stumbled upon ZYpp. That was it. ZYpp uses a SAT solver to manage dependencies. Fast forward. Thanks to the hard work of Nils Adermann and Jordi Boggiano, PHP now has one of the best dependency manager, Composer.

Yes, PHP has a better dependency manager than any other languages.

And thanks to Git, Composer, and the PHP built-in web server, it has never been easier to download/install/test a PHP project.

Want to test Symfony (using PHP 5.4)?

$ composer.phar create-project symfony/framework-standard-edition
$ cd framework-standard-edition
$ ./app/console server:run
Want to test Silex?

$ composer.phar create-project fabpot/silex-skeleton
$ cd silex-skeleton
$ php -S localhost:8888 -t web/
Don't know Composer yet? You should learn about it. Browse Packagist, the main Composer repository: it already has 1900+ packages available and they have been installed more than a million times in less than 3 months.

Next challenge: include the Composer installer in the next PHP version?

Collaboration
Community collaboration is the most important point of this post; the one I'm the most proud of. We start to see better collaboration between PHP projects, even from the very big ones, the ones you would think are large enough to not care about the others.

phpBB, Drupal, eZ Publish, Symfony, and many others (phpDocumentor, PHPUnit, Behat, Zikula, Propel, Doctrine, Midgard, ...) are sharing code. Yes, they are "competitors" but they all understood that cross-pollination was a good thing. And Composer is a good enabler.

Next challenge: Convince even more projects to join the trend.

Conclusion
Let me say it again: PHP is probably not the best language out there, and I'm the first one to scream about its quirks, but PHP is the best web platform... ever.

**Comment by Firedrake969** [comment]
At least cite your sources lol
http://fabien.potencier.org/php-is-much-better-than-you-think.html

**Comment by herohamp** [comment]
@Firedrake969 Sorry I actually had the URL in my clipboard but forgot to past it :P

**Comment by herohamp** [comment]
http://fabien.potencier.org/php-is-much-better-than-you-think.html

**Comment by herohamp** [comment]
And also I know how to use javascript yet I just cannot figure out how to use node

**Comment by Firedrake969** [comment]
Why?
1.  Write JS
2.  `node file.js`

**Comment by herohamp** [comment]
I don't know. I just am having issues learning how to make webpages and stuff like that
</offtopic>

**Comment by Radical-from-Scratch** [comment]
All offtopic posts have been deleted.

**Comment by Jonathan50** [comment]
> All offtopic posts have been deleted.

...no they haven't. And the post redirecting people asking about PHP (which is offtopic) to another issue was deleted?

**Comment by HittmanA** [comment]
@herohamp Please read my latest gitter comment to you.

**Comment by Firedrake969** [comment]
@Jonathan50 tfw @Radical-from-Scratch censors your posts lol

**Comment by ghost** [comment]
I'm not trying to prevent you from posting. I'm just pointing out that  this thread is about bjskistad's retirement and turning it into an argument about PHP is pretty horrible.

**Comment by skistaddy** [comment]
@Radical-from-Scratch :)

**Comment by ghost** [comment]
All of us are better than PHP. PHP is like the only web language I know and if any one of you were sliding off a cliff into lava and I had to remove PHP from the world to get someone to save you I would get rid of PHP.

**Comment by HittmanA** [comment]
Even me?

**Comment by skistaddy** [comment]
XD

**Comment by Radical-from-Scratch** [comment]
Even you. I'll tell you all a secret on the private chat.

**Comment by herohamp** [comment]
I would let HittmanA burn to save Javascript, NodeJS, PHP, BASH, and Everything else! ;P

**Comment by JordanB-1337** [comment]
I would let Hittman burn to save node (even though it sucks)

**Comment by skistaddy** [comment]
@JordanB-1337 Dude, Node is the best for web development.

**Comment by jeandrek** [comment]
Reactions don't work when the conversation is locked :/

**Comment by skistaddy** [comment]
:/

**Comment by as-com** [comment]
*makes popcorn*

**Comment by HittmanA** [comment]
That really kinda (snip &ndash; ಠ_ಠ) me off @herohamp and @JordanB-1337

**Comment by JordanB-1337** [comment]
Well look what happened to Firedrake: https://github.com/Newawe/newawe/issues/37#issuecomment-228045189

And since I blocked him from the org, he can't even edit it back ;P
