### ISSUE TITLE
Authentication MySQL plz :)

### ISSUE THREAD

**Issue by ghost** [Newawe/newawe#37]
I need it for the forumz :)

**Comment by Radical-from-Scratch** [comment]
Pwetty pweez make it yewshabull wiff a get weqwest?

(Pretty please make it usable with a get request?)

**Comment by ghost** [comment]
I'd like something like: newawe.com/api/auth.php?un=-Radical-&password=isbetterthanhittmana

**Comment by haylinmoore** [comment]
ummm no we should use post

**Comment by matthewr6** [comment]
I should just go die in a fire right now.

**Comment by HittmanA** [comment]
^^ 
agree with @Firedrake969

**Comment by ghost** [comment]
No, I wasn't asking about authentication for MySQL, I was talking about for the main website.

Authenticaion for newawe.

As for whether or not we should use POST, that would be fine :)

**Comment by Firedrake969** [comment]
> Authentication MySQL
> wasn't asking about authentication for MySQL
Ok

**Comment by ghost** [comment]
Keyword : FOR Mysql.

I was asking that it be performed via Mysql, not that mysql accounts would be the authenticee. (I just created a new word, authenticee)

**Comment by ghost** [comment]
Locking conversation to prevent firedrake from continuing to question everything I do.

**Comment by haylinmoore** [comment]
Opening this is interesting

**Comment by ghost** [comment]
Are you trying to unlock the conversation?

**Comment by jeandrek** [comment]
OH NO What happened to GitHub's reaction emojis? 😕 😢

**Comment by ghost** [comment]
I think they removed them.

**Comment by jeandrek** [comment]
> I think they removed them.

Nope, I still see them in other repositories. Perhaps you accidentally disabled them for this repo?

**Comment by ghost** [comment]
By _you_ are you actually talking about me, or just Newawe in general.

**Comment by jeandrek** [comment]
Anyone who is able to, because I can't change the settings.

**Comment by ghost** [comment]
That would be either @bjskistad or @herohamp. In theory I am co-owner of development but I still hold the rank of a normal user.

**Comment by jeandrek** [comment]
Oh.

Well, in my repositories, I can't see any settings for reaction emojis.

**Comment by BKFighter** [comment]
I think it's because this is locked. That would be my guess @Jonathan50

**Comment by ghost** [comment]
But locking doesn't apply to him. If it applied, he wouldn't be able to post.

**Comment by BKFighter** [comment]
But @Radical-from-Scratch I'm wondering if that's what it is because I can't see the reactions either.

**Comment by BKFighter** [comment]
I unlocked it and could see reactions, but locked it and couldn't!

**Comment by jeandrek** [comment]
Oh, locking disables reaction emojis for the issue. It's not a big deal.

**Comment by ghost** [comment]
That's true. Anyway, back on topic. Could someone please help with an authentication API for the forums?

**Comment by joker314** [comment]
Well, I don't think using a GET request is at all safe. A POST request might work, but perhaps we could use the same database for the wiki and the forums? Is that possible?

**Comment by skistaddy** [comment]
@joker314 It's possible, you would just store the main site, the forums, and the wiki all in different tables. But since we're implementing documentation, do we need a wiki?

**Comment by JordanB-1337** [comment]
If LilBB is ever finished, I will just use the same thing we did there to do it here.

**Comment by CosmicWebServices** [comment]
LilBB MUST be finished :)

**Comment by JordanB-1337** [comment]
Yeah, it must.

**Comment by CosmicWebServices** [comment]
Never?

**Comment by JordanB-1337** [comment]
@herohamp Seriously, cut it out now.

**Comment by CosmicWebServices** [comment]
@JordanB-1337 that was me 👍

**Comment by JordanB-1337** [comment]
Check your gitter
