### ISSUE TITLE
Credits not available?

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#39]
Terms are available now, but not the credits. I'm gettin a 404 for credits.

**Comment by herohamp** [comment]
Hmm. We need to add it to config.json

**Comment by bjskistad** [comment]
O. Wait, so every project someone makes is going to have to be added to the config file?

**Comment by Radical-from-Scratch** [comment]
Yep >:)

**Comment by herohamp** [comment]
Fixed!

**Comment by Radical-from-Scratch** [comment]
Great!

**Comment by Jonathan50** [comment]
@bjskistad erm hopefully not

**Comment by bjskistad** [comment]
Lol

**Comment by Radical-from-Scratch** [comment]
It was just a mistake calm down
