### ISSUE TITLE
Can I join?

### ISSUE THREAD

**Issue by EvilBashScript** [Newawe/newawe#40]

**Comment by HittmanA** [comment]
Ask @herohamp

**Comment by ghost** [comment]
This is an alt of herohamp.

**Comment by ghost** [comment]
But sure. why not xD

**Comment by haylinmoore** [comment]
I never made the post

**Comment by ghost** [comment]
Promise?

**Comment by haylinmoore** [comment]
the account has been deleted
did one of you guys hack it?

**Comment by ghost** [comment]
https://github.com/EvilBashScript -- Looks not deleted. 

The account I assigned was EvilLinuxKernel.

**Comment by haylinmoore** [comment]
wait WTH someone made that account trying to be me!

**Comment by ghost** [comment]
I contacted support, but for whatever reason they deleted yours.

**Comment by skistaddy** [comment]
@herohamp See the latest removal in the audit log: https://github.com/organizations/Newawe/settings/audit-log?q=action%3Ateam.remove_member . The account was deleted somehow.

**Comment by ghost** [comment]
The account was deleted. I reported EvilBashScript for impersonating EvilLinuxKernel, but they deleted the real one instead.

**Comment by haylinmoore** [comment]
I deleted the real one. I did not relize It was EvilBashScript who made the topic and though EVilInux had been hacked

**Comment by ghost** [comment]
Oh. Please contact support as well so they can fix this mess.

**Comment by jeandrek** [comment]
Who is @ghost, why where they assigned and why is there name "Deleted User"?

**Comment by ghost** [comment]
I didn't assign "ghost" I assigned @EvilLinuxKernel but then they got deleted.

**Comment by jeandrek** [comment]
Who's that?

**Comment by ghost** [comment]
It's a prank alt that herohamp made.

**Comment by HittmanA** [comment]
Guys this is an account I made. I wanted to try out using GitHub api and made this account for that.

**Comment by haylinmoore** [comment]
then wth did you use my icon?

**Comment by ghost** [comment]
And a similar username to his?

**Comment by haylinmoore** [comment]
yeah

**Comment by HittmanA** [comment]
Sorry I just thought it would be funny to have EvilLinuxKernal and EvilBashScript.

**Comment by jeandrek** [comment]
I don't think @EvilBashScript's icon looks anything like @herohamp's.

**Comment by haylinmoore** [comment]
@Jonathan50 no the icon he has is the one I had for EvilLinuxKernal and that icon is my gravatar

**Comment by haylinmoore** [comment]
see
https://s.gravatar.com/avatar/f6ddc012a0cf8441d110be543a43c9e9?s=80

**Comment by haylinmoore** [comment]
plus its my youtube icon and you can find all the documents from where I made it at http://work.herohamp.xyz/Projects/Youtube/herohamp/icon/

**Comment by jeandrek** [comment]
Oh. Why did @EvilLinuxKernel get deleted?

**Comment by haylinmoore** [comment]
I though it was hacked so removed it

**Comment by HittmanA** [comment]
I will change the image.

**Comment by haylinmoore** [comment]
you can keep it. It makes the account look evil

**Comment by HittmanA** [comment]
Thanks. Sorry for the confusion I caused.
