### ISSUE TITLE
NEWAWE IRC

### ISSUE THREAD

**Issue by ghost** [Newawe/newawe#42]
Since people are reluctant to use Gitter (not looking at anyone in particular) I've created an IRC channel if anyone wants to use it.
Here are the steps for getting in: 

_removed, I need the admin's input first_

**Comment by skistaddy** [comment]
I approve.

**Comment by ghost** [comment]
Should it replace Gitter or will we have 2 chats?

**Comment by ghost** [comment]
It doesn't matter to me I'm just wondering.

**Comment by robinp7720** [comment]
Gitter has an IRC frontend? just stay with Gitter. Having more then one chat is just to complicated

**Comment by haylinmoore** [comment]
Agreed

**Comment by haylinmoore** [comment]
And where is the gitter irc?

EDIT by -Radical- : see my post below

**Comment by robinp7720** [comment]
https://irc.gitter.im/
I use it with irssi on my server. Allows me to be online 24/7 and recieve all messages

**Comment by haylinmoore** [comment]
Hmm nice

**Comment by jeandrek** [comment]
I won't be able to join either chat, sorry.

Would someone be able to join on IRC but not on Gitter (or the other way round)?

**Comment by haylinmoore** [comment]
Why can't you join anything?

**Comment by haylinmoore** [comment]
@Jonathan50 ^^^^^

**Comment by skistaddy** [comment]
His parents probably don't like chats.

**Comment by haylinmoore** [comment]
Oh.... I have been using IRC for various things since I was 9 :P

**Comment by jeandrek** [comment]
Yeah, I'm not allowed.

**Comment by skistaddy** [comment]
:)

**Comment by ghost** [comment]
@herohamp That won't work. Gitter IRC doesn't work.

@Jonathan50 Fine, you can probably use forums, right? I'll make forums. Just for Jon. That I'd like everyone to use. For Jon. For everyone. For Jon. And everyone. And Jon. And everyone except Jon. And Jon.

@robinp7720 The reason why I was waiting for admin approval was we were discussing this being _instead_ of Gitter.

**Comment by robinp7720** [comment]
@Radical-from-Scratch Why use IRC in the first place? It's inferior to Gitter in almost all possible ways. And the Gitter IRC works flawlessly. I use it with irssi on my server. Why use a server? because due to the way irc works, you loose chat history when you're not connected. For a developer chat, chat history is extremely important.

And lastly, you're all discussing things we've already discussed and have already setup. We **have** a chat. We don't need to replace it with something inferior. Focus on Newawe, not on the way we communicate when we have a fully functional feature rich chat method. Currently, I have commited more then twice the amount of lines you have. Please, instead of trying to change things that won't affect Newawe in any positive way and instead actualy help with the project. For example, you can help out with the router branch and help implement routing.

**Comment by ghost** [comment]
That was a nice novel, but criticizing everything everyone does isn't helping anything.

**Comment by jeandrek** [comment]
> That was a nice novel, but criticizing everything everyone does isn't helping anything.

What novel are you talking about?

**Comment by robinp7720** [comment]
@Jonathan50, he means the comment that so kindly pointed out that irc lacks in features and how hr wants to change everything while not actually working much on the project itself.

@Radical-from-Scratch, didn't I tell you to stop editing/deleting my comments? It wasn't spam or the similar.  It was a detailed post as to why not to switch to irc.

**Comment by as-com** [comment]
@robinp7720 Here's your message:

> Why use IRC in the first place? It's inferior to Gitter in almost all possible ways. And the Gitter IRC works flawlessly. I use it with irssi on my server. Why use a server? because due to the way irc works, you loose chat history when you're not connected. For a developer chat, chat history is extremely important.
> 
> And lastly, you're all discussing things we've already discussed and have already setup. We have a chat. We don't need to replace it with something inferior. Focus on Newawe, not on the way we communicate when we have a fully functional feature rich chat method. Currently, I have commited more then twice the amount of lines you have. Please, instead of trying to change things that won't affect Newawe in any positive way and instead actualy help with the project. For example, you can help out with the router branch and help implement routing.

**Comment by ghost** [comment]
Okay I think you're all missing something important. I had already decided to not use IRC more than 24 hours before that comment was posted.

Plus, you still decided that posting gratuitous comments about how I do nothing but disrupt the project and you're the one doing all of the work is, in any way, acceptable.
