### ISSUE TITLE
What happened to the logo....

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#42]
Check the live version.

**Comment by herohamp** [comment]
Gosh. At school ATM will fix when I get back

**Comment by bjskistad** [comment]
K. I'm at school too.

**Comment by Radical-from-Scratch** [comment]
I am not at school right now, but have check from school before :P

**Comment by bjskistad** [comment]
Lol

**Comment by Radical-from-Scratch** [comment]
I am writing *this* message from school

**Comment by DrKat123** [comment]
What the?

**Comment by DrKat123** [comment]
i'm responsible for the logos and images, so i guess i'd assign myself

**Comment by bjskistad** [comment]
I meant CSS, it isn't very square. How's the new logo coming.

**Comment by DrKat123** [comment]
ok. done

**Comment by herohamp** [comment]
Pic?

**Comment by bjskistad** [comment]
Hampton will upload for you.

**Comment by herohamp** [comment]
ok. I updated the main site

**Comment by herohamp** [comment]
I need to need to screw around with the css

**Comment by DrKat123** [comment]
:stuck_out_tongue:

**Comment by bjskistad** [comment]
Yeah. Make the logo go farther left. So it covers the white.

**Comment by DrKat123** [comment]
should we delete favicon.png?

**Comment by bjskistad** [comment]
Yeah.

**Comment by herohamp** [comment]
can somebody try the CSS. I can't ATM

**Comment by DrKat123** [comment]
okay

**Comment by bjskistad** [comment]
Ok.

**Comment by herohamp** [comment]
what is the ssh port again? I forgot?

**Comment by bjskistad** [comment]
I have no idea.

**Comment by DrKat123** [comment]
![looks gr8](http://prntscr.com/astcs3)

**Comment by DrKat123** [comment]
umm wat

**Comment by DrKat123** [comment]
the image is broken

**Comment by DrKat123** [comment]
gonna post another one...

**Comment by herohamp** [comment]
ok.

**Comment by DrKat123** [comment]
![does this work? if you see this text the you might have been h4x3d](https://keybase.pub/drkat123/for_newawe.png)

**Comment by DrKat123** [comment]
huh

**Comment by DrKat123** [comment]
![this is not going to work... :confused:](https://keybase.pub/drkat123/for_newawe.png)

**Comment by DrKat123** [comment]
huh

**Comment by DrKat123** [comment]
thisandagain plz explain

**Comment by DrKat123** [comment]
![for_newawe](https://cloud.githubusercontent.com/assets/15071615/14578402/88eea03c-03b1-11e6-90ee-2aba7b1713e2.png)

**Comment by DrKat123** [comment]
argh finally

**Comment by DrKat123** [comment]
![for_newawe](https://cloud.githubusercontent.com/assets/15071615/14578412/c65f5128-03b1-11e6-8e27-b9330376b655.png)
phone simulation

**Comment by herohamp** [comment]
My old site?

**Comment by DrKat123** [comment]
huh? it's newawe.herohamp.xyz... argh forgot to add port 8000 to the url

**Comment by herohamp** [comment]
xD sorry I am having issues with hosting on port 80 from my computer and linking to port 8000 on my pi.

**Comment by DrKat123** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15071615/14578442/6ecbe736-03b2-11e6-8530-fb500c40ec96.png)
ಠ_ಠ

**Comment by DrKat123** [comment]
ಠ~ಠ-ಠ~ಠ-ಠ~ಠ

**Comment by Radical-from-Scratch** [comment]
Yeah, we use port 8000 to avoid dDoS attacks when we're not quite secure yet. If you don't, you get his personal site.

**Comment by DrKat123** [comment]
:stuck_out_tongue: 
Why not use cloudflare?

**Comment by Radical-from-Scratch** [comment]
Because cloudflare does not give the sufficient needs nessessary to running this website

**Comment by DrKat123** [comment]
oh :stuck_out_tongue:

**Comment by DrKat123** [comment]
anyway

> ![screenshot_1](https://cloud.githubusercontent.com/assets/15071615/14578442/6ecbe736-03b2-11e6-8530-fb500c40ec96.png)
> ಠ_ಠ

**Comment by Radical-from-Scratch** [comment]
That's unforunate. What's also unfortunate is that I don't develop the main site and cannot do anything about it.

**Comment by DrKat123** [comment]
oh, :stuck_out_tongue:

**Comment by DrKat123** [comment]
Why not use foundation for the main site? it has more features than bootstrap
http://foundation.zurb.com/

**Comment by DrKat123** [comment]
And it's still mobile first

**Comment by Radical-from-Scratch** [comment]
nah

**Comment by Jonathan50** [comment]
Using port 8000 doesn't protect you from DDoS. And you're unlikely to be targeted anyway (not every bad guy owns a personal botnet)

**Comment by herohamp** [comment]
Dude I host other things than just newawe ATM so unless you get figure out how to virtual host newawe at port 80 for me then it will stay 8000

**Comment by DrKat123** [comment]
okay

**Comment by DrKat123** [comment]
btw somebody should fix this:
![](https://cloud.githubusercontent.com/assets/15071615/14578442/6ecbe736-03b2-11e6-8530-fb500c40ec96.png)
