### ISSUE TITLE
Cross-site-scripting (XSS)

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe#44]
We aren't removing special chars from user-input. This is very dangerous. Currently I managed to get node.js to give e a console.error, but if I had enough time, something that could potentially delete all user accounts (or somthing similar) could be possible. The way it works is that user-input can be malicious, an example below:
`" console.log(data.allUsers); "` 
The quotes are intentional. The above code might output all of the usernames, hashes f passwords, and possibly emails. The solution is to replace all special chars with their equivalents in html, see below:
`< &lt;`
`> &gt;`
`& &amp;`
`" &quot;`
`' &apos;`
`\ &Backslash;`
So, we need to do a bit of redesigning maybe?

**Comment by Radical-from-Scratch** [comment]
I agree.

**Comment by joker314** [comment]
Ok, so should I add this:
`
userinput = userinput.replace("&", "&amp;");
userinput = userinput.replace("<", "&lt;");
userinput = userinput.replace(">", "&gt;");
userinput = userinput.replace(" ", "&nbsp;");
`
And should I also close this issue?

**Comment by bjskistad** [comment]
They just shouldn't be able to have those chars in their username.

**Comment by joker314** [comment]
I added a script to prevent it, so usernames will be fine. I have created a function that does the above though.

**Comment by joker314** [comment]
Ok to close?

**Comment by bjskistad** [comment]
Yeah
