### ISSUE TITLE
Minify css, js etc at release?

### ISSUE THREAD

**Issue by CosmicWebServices** [Newawe/newawe#45]
By the way I am not on the team at this time just helping out.

**Comment by jeandrek** [comment]
Why minify PHP? I think the main reason to minify JS and CSS is for faster download times. I guess minifying PHP could make it parse faster.

**Comment by CosmicWebServices** [comment]
To speed up the code and page load time and help SEO

**Comment by haylinmoore** [comment]
for PHP ;P that makes no sense

**Comment by CosmicWebServices** [comment]
OK then no for PHP its ur site :)

**Comment by CosmicWebServices** [comment]
Also I made two prs

**Comment by JordanB-1337** [comment]
Yeah, we're currently using regular PHP.

**Comment by Jonathan50** [comment]
> Yeah, we're currently using regular PHP.

?

**Comment by joker314** [comment]
Yes well I think we should minify JS and CSS but am not sure about PHP. I mean, removing unnecessary whitespace will cut down parsing time, right? So a bit of minifying wouldn't hurt

**Comment by CosmicWebServices** [comment]
yep

**Comment by joker314** [comment]
What language is the PHP compiler/interpreter written in?

**Comment by haylinmoore** [comment]
I dunno

**Comment by haylinmoore** [comment]
PHP is an interpreted language. You need a separate program to run PHP code, the computer does not run the program directly. That separate program, the PHP interpreter, is itself written in C.

C# is a compiled language, but it is not compiled to machine code. Instead, it is compiled to a specialist language, byte code, to be run on a virtual machine. Java is another example of such a setup. You could see it as a hybrid between compilation and interpretation, where the virtual machine is an interpreter. The virtual machine for C# (the CLI, or Common Language Infrastructure) is written in C++.

**Comment by haylinmoore** [comment]
I found out

**Comment by CosmicWebServices** [comment]
Look at the first answer http://stackoverflow.com/questions/3095424/minify-html-php

**Comment by CosmicWebServices** [comment]
But there is this: https://github.com/searchturbine/phpwee-php-minifier

**Comment by JordanB-1337** [comment]
Minifying code can make it run faster, but I think minifying CSS is totally pointless.

What does everyone else think?

**Comment by CosmicWebServices** [comment]
minifying css is not 100% pointless it helps with file size not speed

**Comment by JordanB-1337** [comment]
It would only removea few bytes, but sure, minify your heart out! :)

**Comment by CosmicWebServices** [comment]
:P
