### ISSUE TITLE
two-factor auth support?

### ISSUE THREAD

**Issue by CosmicWebServices** [Newawe/newawe#48]
I know how you could do but is it priority at the moment?

**Comment by JordanB-1337** [comment]
No, not right now. Plus, out of all of us in Newawe, as-com is the _only_ one who uses it on their GitHub account (and he resigned). So I can't say we like it that much xD

It's not on our to-do list, but you could make one and we might use it :)

**Comment by CosmicWebServices** [comment]
Yep OK I will not do it now

**Comment by JordanB-1337** [comment]
Well I'm not saying you _can't_

**Comment by CosmicWebServices** [comment]
I know but I am not part of the team and I do not want to do something not part of the plan
