### ISSUE TITLE
How are we hosting the blog?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#54]
We are using WordPress for the blog, if I'm not misunderstood. How did we pay for the custom domain? (blog.newawe.com) You have to if you use WordPress.

**Comment by as-com** [comment]
capital_P_dangit()
https://codex.wordpress.org/Function_Reference/capital_P_dangit https://codex.wordpress.org/Function_Reference/capital_P_dangit

**Comment by skistaddy** [comment]
Wowwwwww. 😆

**Comment by haylinmoore** [comment]
Barran I am hosting the blog

**Comment by skistaddy** [comment]
Really? RasPi?

**Comment by haylinmoore** [comment]
well more like I am hosting it on a hosting website.

**Comment by skistaddy** [comment]
Oh, how are you using WordPress?

**Comment by jeandrek** [comment]
wordpress.com is a blog hosting service that uses the software from wordpress.org.

**Comment by JordanB-1337** [comment]
Per Jonathan, WordPress is open source software, they just offer hosting for you.
