### ISSUE TITLE
Should we support some form of markdown?

### ISSUE THREAD

**Issue by bjskistad** [Newawe/newawe#54]
Should we support markdown in comments? We could use GitHub flavoured markdown.

**Comment by DrKat123** [comment]
yeah

we can use the GH MD api

**Comment by bjskistad** [comment]
K.

**Comment by DrKat123** [comment]
Just send the api the raw md and it'll return the HTML

**Comment by Jonathan50** [comment]
Let's get a working site before we start doing _this_...

**Comment by bjskistad** [comment]
Lol. I'll close the issue for now. XD  We don't even have comments yet. XD

**Comment by DrKat123** [comment]
:stuck_out_tongue:
