### ISSUE TITLE
Crash on registering with invalid username

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe#55]
```
someone attempted to sign up with the username: <<<testIfXSSDefenseInUNameWorks>>> but it contained invalid characters
/home/pi/Desktop/newawe-node/server.js:76
	return substitute(readFile("pages/global.html"),{"content": substitute(readFile("pages/html/" + config.pages[pageName].file), {"page-title": config.pages[pageName].title, "site-title": config.pages[pageName].siteTitle})});
	                                                                                                                      ^

TypeError: Cannot read property 'file' of undefined
    at globalSiteText (/home/pi/Desktop/newawe-node/server.js:76:120)
    at register (/home/pi/Desktop/newawe-node/server.js:195:19)
    at /home/pi/Desktop/newawe-node/server.js:250:5
    at IncomingMessage.<anonymous> (/home/pi/Desktop/newawe-node/server.js:213:34)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by bjskistad** [comment]
It crashed?

**Comment by herohamp** [comment]
Like 8 times xD

**Comment by DrKat123** [comment]
Woah

You should try resetting the server

**Comment by joker314** [comment]
Sorry about that, I was just testing. But at least it will not happen in real life now. Just delete that account and it should work.

**Comment by joker314** [comment]
BTW, I added a defense against that, why didn't it work?

**Comment by joker314** [comment]
I KNOW WHAT HAPPENED
THE FILE DOES NOT EXIST
SEE SERVER.JS IT CONTAINS A
COMMENT I LEFT
SAYING A FILE DOES NOT EXIST
WE NEED TO CRATE IT
SORRY FOR SHOUTING, I 
THOUGHT THIS MIGHT BE IMPORTANT

**Comment by joker314** [comment]
Check the pull requests

**Comment by joker314** [comment]
Ok, I think I have fixed the bug. Tell me when your server updates herohamp, and can we try the

> <<<XSSTest>>>
again, to make sure it works. But first the config.json, and a new file I created must update, or a similar error will appear.

**Comment by joker314** [comment]
I have edited the priority, becuase the bug has been fixed (I think). Is the server healthy?

**Comment by herohamp** [comment]
I updated and got a new error!

pi@webpi ~/Desktop/newawe-node $ node server.js
A past server configuration file already exists!
undefined:20
        "signupFailunv": {"title":"Signup", "siteTitle":"signup", "file":"signupFailUsernameInvalid.html"}
        ^
 
SyntaxError: Unexpected string
    at Object.parse (native)
    at Object.<anonymous> (/home/pi/Desktop/newawe-node/server.js:47:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by joker314** [comment]
Well that is my line of code, but I donn't know why it caused an error, I will look into that.

**Comment by joker314** [comment]
LOL, it was a missing comma. Try it now?

**Comment by joker314** [comment]
Changed priority because it should work this time. The GH editor was highlighting a bit of that line in dark red, but I thought nothing of it. So now it should work, and I have thus changed the priority down. After the update, we should test if the bug remains

**Comment by Radical-from-Scratch** [comment]
If we don't fix this, here is what will happen: https://xkcd.com/327/

**Comment by joker314** [comment]
I fixed it, everything is fine, but that SQL Injection joke is excellent! (Even though we are not using SQL [yet?])

**Comment by Radical-from-Scratch** [comment]
Um, we, are, at some point, going to have to use SQL for the forums and wiki, so we may as well use them for the main site. I'm going to wait before closing, though, because I want to make sure it's really fixed.

**Comment by joker314** [comment]
Good idea. BTW, if anybody needs it, I made a function near the to of server.js, to escape html characters:
<, >, &, [space], ", '
And returns the string with the "evil" characters replaced with their &word; equivalents. It does not escape backslashes, nor unicode escape chars (they can be a bit dangerou, e.g. NULL)

**Comment by joker314** [comment]
herohamp's site loaded, does that mean it is fixed?

**Comment by joker314** [comment]
Should I try and crash it again with
`<<<XSSTest>>>`
It shouldn't work,and if we don't find it now, we might never. But you would have to sacrifice a possible (but unlikely) server crash.

**Comment by bjskistad** [comment]
Close? I think we fixed.

**Comment by joker314** [comment]
Agreed. (I just added extra styling with the user-friendly errors that don't crash the server, do you updte the server every 15 mins?)

**Comment by bjskistad** [comment]
Yeah, it runs on Hampton's Pi though.

**Comment by joker314** [comment]
Good. Shall we close then?
