### ISSUE TITLE
What do we need to do to get going again?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#56]
Ok, everybody. We need to get Newawe running again. What do we need to do to do it? I've got plenty of time as of now, and I can contribute as much as possible. I now know PHP, so that will help. What do we need to do? Do we need DBs? I for one, need the creds to the site. Whoever has em, mail em to me at baranjskistad@gmail.com
# List of stuff to do
- Implement a Framework

**Comment by JordanB-1337** [comment]
With none of the content, naturally.

**Comment by jeandrek** [comment]
There? (We can edit any comment :P sorry)  --edited by masterex1000 Jonathan50 was here111111
Yay Jonathan50 was here again
and again~Jonathan50
Yes Jonathan50 edited again
Guess who edited again? Jonathan50!!!

**Comment by JordanB-1337** [comment]
@Jonathan50 When I got here, it just said "remake of the original" and nothing else.

**Comment by jeandrek** [comment]
I know that. I edited it :P

**Comment by skistaddy** [comment]
@JordanB-1337 Naturally. 😆

**Comment by JordanB-1337** [comment]
Yeah.

**Comment by haylinmoore** [comment]
No offence but newawe is dead

**Comment by skistaddy** [comment]
Ok, so, one thing I think we need to implement is a framework of some sort.

**Comment by skistaddy** [comment]
@herohamp Says the co-owner...

**Comment by haylinmoore** [comment]
I know that is why it is very bad I am saying it as it is dead

**Comment by skistaddy** [comment]
That's why we need to get it "alive".

**Comment by haylinmoore** [comment]
ok I am thinking a pep rally on the gitter

**Comment by JordanB-1337** [comment]
I told you hamp thought it was dead.

**Comment by herohamp** [comment]
Umm Jordan a little harsh

**Comment by JordanB-1337** [comment]
Bjskistad check your gitter.

**Comment by haylinmoore** [comment]
So what should we do as know one cares much anymore.

**Comment by skistaddy** [comment]
Maybe that pep rally.

**Comment by HittmanA** [comment]
I dont think a pep rally would help...

**Comment by HittmanA** [comment]
Ok Once Lil-Coders.org is released officially and is on a stable course I will begin deving on Newawe again. In the past 6 months (or so) that I have been gone I have learned an INCREDIBLE (like 10x more) amount more about programming. I would be happy to help again!

**Comment by haylinmoore** [comment]
^^^^^^^^^^^ same

**Comment by CosmicWebServices** [comment]
^^^^^^ same

**Comment by skistaddy** [comment]
^^^^^^ same.  

I even created a website in PHP since I quit. 😆

**Comment by JordanB-1337** [comment]
^^^^^^^^^^^^^^^ same

**Comment by jeandrek** [comment]
So many carets. </offtopic>

**Comment by JordanB-1337** [comment]
They are good for your eyes, bruh.

**Comment by skistaddy** [comment]
@herohamp What are we using to manage DNS, subdomains, etc? Are we still using Cloudflare? If so, can you mail me the creds?

**Comment by JordanB-1337** [comment]
Currently, we are using Gwiddle. But I can't mail them to you without your email. ;P

**Comment by skistaddy** [comment]
baranjskistad@gmail.com

**Comment by JordanB-1337** [comment]
Okay, I will do that when I get home from school.

**Comment by skistaddy** [comment]
K.

**Comment by haylinmoore** [comment]
Ok we use cloudflare for DNS and gwiddle for blog and toolserver hosting.

**Comment by skistaddy** [comment]
K.

**Comment by skistaddy** [comment]
@JordanB-1337 ...

**Comment by skistaddy** [comment]
@herohamp Do you have the creds?

**Comment by haylinmoore** [comment]
@bjskistad https://gitter.im/bjskistad

**Comment by JordanB-1337** [comment]
That link won't work, hamp ;P

Use this one instead.

http://gitter.im/JordanB-1337

Remember to put your own name when giving a link to a dm :)

**Comment by csf30816** [comment]
"...Do we need DBs?..." Of course! I do not even know of a way to create a sign up/login/share feature without those good ol' MySQL DBs

**Comment by skistaddy** [comment]
@csf30816 the reason that question was asked was because we were mostly implying the question of who was going to buy the databases, we also need to know if @PolyEdge got databases with hosting or not.

**Comment by skistaddy** [comment]
I honestly don't know why we switched back to PHP, mostly everyone here knows JavaScript therefore Node.js will

1. Be more efficient.
2. Be cleaner.
3. Be the most modifiable.

**Comment by haylinmoore** [comment]
We switched to PHP because I was an idiot and suggested it and got some other people to vote for the change. I currently have a VPS and would be happy to host newawe

**Comment by JordanB-1337** [comment]
Yes, per herohamp. I don't know where the "mostly everyone here knows JavaScript" came from---I hear from many people that they don't know any node and only know PHP.

**Comment by csf30816** [comment]
@herohamp And who was that idiot? I personally like PHP better.

**Comment by JordanB-1337** [comment]
Nobody asked you. This conversation is about the Newawe developers and no one else.

**Comment by haylinmoore** [comment]
Sorry @csf30816 but we are limiting this thread to devs only

**Comment by skistaddy** [comment]
@JordanB-1337, JavaScript is simply a necessity, I don't know a developer that hasn't done something with it. It's easy to pick up if you have had experience with any other language, and it is it's own server, so we don't need to install Apache or Nginx. Plus, if we can do all our coding in one language on the server side and the client, then we will be more efficient.

**Comment by CosmicWebServices** [comment]
I vote for Nodejs because it will have very fast development times and those who do not know it can learn it generally quickly.

**Comment by haylinmoore** [comment]
I think we should restart the nodeJS repo and code it using express instead of http. and for serving we should use nginx as a reverse proxy that can handle caching, letencrypt support, etc

**Comment by skistaddy** [comment]
+1

**Comment by haylinmoore** [comment]
https://github.com/Newawe/node

**Comment by JordanB-1337** [comment]
PHP > Node > PHP > Node

we're very organized :P

**Comment by haylinmoore** [comment]
Its just changing opinions....

**Comment by JordanB-1337** [comment]
Changing opinions too often

**Comment by JordanB-1337** [comment]
Also check your gitter

**Comment by PolyEdge** [comment]
@bjskistad I bought the domain and the domain only. There is no hosting and I barely have enough money to support the domain ATM, so I hope somebody else can handle it

**Comment by PolyEdge** [comment]
Also kinda sad that I don't even have access to the CF of whoever's managing the domain
![screenshot_3](https://cloud.githubusercontent.com/assets/13187260/26749663/e2f8dac4-47cc-11e7-824c-42eb0b1f424c.png)

**Comment by haylinmoore** [comment]
I can host it. Dm me on gitter for the login xD

Infact I am currently hosting dev.newawe.com

**Comment by PolyEdge** [comment]
home-host?

**Comment by PolyEdge** [comment]
I'm kinda held down rn as I try to tame my scratch cloud scripts after HTTP polling broke on me

**Comment by haylinmoore** [comment]
Nope a VPS hosted by hostus. But I also have some home servers that I can host on.

**Comment by PolyEdge** [comment]
I saw that video of your server you got 

With the stuff I run I wouldn't be able to sleep at night from the cpu fans 

![screenshot_4](https://cloud.githubusercontent.com/assets/13187260/26749775/1679e300-47cf-11e7-801a-2240438ed2c8.png)

**Comment by PolyEdge** [comment]
My scripts are doing a good job of destroying my internet rn, usually that's my job

**Comment by PolyEdge** [comment]
can we move to gitter?

**Comment by haylinmoore** [comment]
Yup

**Comment by haylinmoore** [comment]
Meet me there

**Comment by RonSkons** [comment]
School's out for me. Any way we can get going again? I have all summer.

**Comment by PolyEdge** [comment]
Everyone the domain was in grace from Jun 16-20

sorry bout that xd

**Comment by haylinmoore** [comment]
I can still connect. Did you rebuy it?

**Comment by PolyEdge** [comment]
yeah

**Comment by PolyEdge** [comment]
I had no money up till that point so I was worrying a lot

**Comment by skistaddy** [comment]
lol

**Comment by baranskistad** [comment]
Moved to #72

**Comment by haylinmoore** [comment]
New Issue

**Comment by haylinmoore** [comment]
https://github.com/newawe/newawe-node/issues/128
