### ISSUE TITLE
Test website where we can see our code?

### ISSUE THREAD

**Issue by HittmanA** [Newawe/newawe#58]
We need to get a test website for a live demo of the code.

**Comment by JordanB-1337** [comment]
We have dev.newawe.com -- but it must be manually updated.

**Comment by haylinmoore** [comment]
I will look into setting up heroku.

**Comment by haylinmoore** [comment]
it will auto update

**Comment by skistaddy** [comment]
I can do it.

**Comment by skistaddy** [comment]
@herohamp Did you create it already? Because `newawe.heruokuapp.com` exists.

**Comment by JordanB-1337** [comment]
I have a solution that's better than Heroku, we're currently looking into using it for LilCoders as well. 


BJ, I will dm you the name.

**Comment by haylinmoore** [comment]
no

**Comment by haylinmoore** [comment]
https://newawe-test.herokuapp.com/

**Comment by herohamp** [comment]
we get a 500 thou

**Comment by haylinmoore** [comment]
it auto updates as well!

**Comment by joker314** [comment]
Shall we close the issue then?

**Comment by CosmicWebServices** [comment]
Think so
