### ISSUE TITLE
reCAPTCHA not working?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#60]
On https://newawe-test.herokuapp.com/login the reCAPTCHA errors like this

```
ERROR for site owner:
Invalid domain for site key
```

**Comment by haylinmoore** [comment]
We just need to reset google reCAPTCHA. I will look into in about 30 mins

**Comment by skistaddy** [comment]
K.

**Comment by CosmicWebServices** [comment]
This was fixed
