### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by jeandrek** [Newawe/newawe#64]
Scrolling on the website just doesn't work.

**Comment by jeandrek** [comment]
It's because of the `overflow:hidden` in

```
style="overflow:hidden;height:100%;width:100%"
```

, which is on both the `html` and the `body`. Also, the styles should be in a CSS file, not in attributes.

**Comment by jeandrek** [comment]
#65 should fix this.

**Comment by jeandrek** [comment]
It works now: https://newawe-test.herokuapp.com/signup

**Comment by skistaddy** [comment]
Why do we need scrolling on the sign up page. It doesn't even go that far down.

**Comment by jeandrek** [comment]
It does on my screen (at 1366x768), I can't see the CAPTCHA until I scroll down. And other pages don't show completely on my screen either.

**Comment by skistaddy** [comment]
Oh yeah. (Sorry, I sometimes forget that the world doesn't revolve around me.)
