### ISSUE TITLE
Sign up makes no request (and the log in page throws an error)

### ISSUE THREAD

**Issue by jeandrek** [Newawe/newawe#66]
Because the JavaScript for the sign up page and log in page are in the same file which is loaded on both.

**Comment by HittmanA** [comment]
I'll take a look.

**Comment by HittmanA** [comment]
Where would this be under? /assets/javascripts/register.js ?

**Comment by jeandrek** [comment]
Now there are no more JS errors but registration still doesn't work. Just get an empty response with status 500.

**Comment by HittmanA** [comment]
Hmmm

**Comment by HittmanA** [comment]
That most likely means a php error

**Comment by HittmanA** [comment]
Ill (try to) take a look.

**Comment by HittmanA** [comment]
Could it be an error with the DB credentials?

**Comment by skistaddy** [comment]
Possibly, but I think that something's going wrong with the POST request, it's not submitting anything.
