### ISSUE TITLE
Difference between /home and root?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#68]
Why does `/home` and root have the same HTML? Why not just make `/home` point to root?

**Comment by haylinmoore** [comment]
I will set that up eventully

**Comment by skistaddy** [comment]
bump

**Comment by 109C** [comment]
@baranskistad But this is just an issue, not a thread.

**Comment by skistaddy** [comment]
I know, just trying to bring attention back to it.

**Comment by haylinmoore** [comment]
I'm going to close this as we are going to rewrite
