### ISSUE TITLE
Is newawe secure?

### ISSUE THREAD

**Issue by CosmicWebServices** [Newawe/newawe#70]

**Comment by CosmicWebServices** [comment]
Just close? @herohamp

**Comment by haylinmoore** [comment]
pointless issue. unless your propose a issue then keep it closed

**Comment by JordanB-1337** [comment]
I agree with herohamp. Not only does three words not merit an issue, you would need to provide an example of how it is not secure.

**Comment by Jonathan50** [comment]
Um, it's a question, it isn't saying that newawe IS insecure. And the wontfix labels only make sense on bugs.

**Comment by CosmicWebServices** [comment]
Thanks finally someone understands @Jonathan50

**Comment by jeandrek** [comment]
Seriously??? That was not justified.

**Comment by haylinmoore** [comment]
How @Jonathan50 all we said was "unless you have a real issue or example please keep this closed."

**Comment by jeandrek** [comment]
I said that it is a _question_ and that it doesn't say that Newawe _isn't_ secure, and that the "wontfix" label only makes sense on issues that are for bugs. And then my comment got deleted.
