### ISSUE TITLE
I'm an admin but not an owner?

### ISSUE THREAD

**Issue by PolyEdge** [Newawe/newawe#71]
I'm an admin here (@herohamp added me a while ago, too lazy to find on gitter), but not an owner?
Are all admins supposed to be owners or am I missing something here?

**Comment by JordanB-1337** [comment]
I've wondered about that as well. I will ask the mega-owner if you should be owner.

**Comment by JordanB-1337** [comment]
I was under the impression that you were an admin a while ago, but I'm not sure what's going on now.

I might get in trouble for making you owner, so I will just leave you as member for now. But if you want any owner things done, just ask any owner and they can help :)

**Comment by skistaddy** [comment]
We weren't sure how active you were going to be, so we gave you executive rights, just not official executive powers. If you would like, we can promote you to an owner.

**Comment by JordanB-1337** [comment]
I don't recall that conversation ever being had, but I guess you would know better than me xD

**Comment by skistaddy** [comment]
XD I'm pretty sure that it was made by Hampton and I, before you were elected as an admin.

**Comment by JordanB-1337** [comment]
Oh. I must be losing track of time. Does Newawe have, like, a google calendar or something?

**Comment by skistaddy** [comment]
No XD

**Comment by JordanB-1337** [comment]
Go here: http://calendar.google.com/Newawe

Just kidding, I didn't make that. Idek if that's how their url system works xD

**Comment by skistaddy** [comment]
404 lol

**Comment by JordanB-1337** [comment]
> Just kidding, I didn't make that.

**Comment by JordanB-1337** [comment]
It should be like on Discord where you can make your own reactions.

**Comment by JordanB-1337** [comment]
So, I think the final descision for this issue is: @bjskistad can if he wants to, but he hasn't yet.
