### ISSUE TITLE
Is this project still going?

### ISSUE THREAD

**Issue by csf30816** [Newawe/newawe#72]
This is a really cool idea, but the website looks the same as it did last year. Are you having trouble?

**Comment by csf30816** [comment]
Because single handily I made a full blown social network from scratch in one week.

**Comment by haylinmoore** [comment]
link?

**Comment by CosmicWebServices** [comment]
I did also @csf30816

**Comment by RonSkons** [comment]
I would love to work more on this project when school gets out in about a month.

**Comment by csf30816** [comment]
@herohamp It was phpsocial.x10.biz (not very creative) but it expired. I had twenty - almost thirty users

**Comment by skistaddy** [comment]
@csf30816, this project is a bit different than most social networking sites. Instead, we are sharing huge files with each other, and playing those files too. So not only do we have to

- Create user pages
- Create projects
- Plus CSS, HTML, and JS.

But we also have to have

- A huge database
- A bunch of devs
- Support for new types of projects
- Support for projects in general
- Moderators that know how to code

So we are up more than just a social networking site, plus we are all busy students, *and* we want to work on our own projects. 

Yes, we'd like to get this back up and running, but it simply at this point seems like more of a bother than it is worth.

**Comment by skistaddy** [comment]
Another thing about single-handedly coding a project is that you don't have to figure and out what your fellow developers' code is doing. Since having a bunch of devs in a necessity for us, this is a bit of a problem.

**Comment by skistaddy** [comment]
@csf30816 I'm gonna add you to our dev team, since you want to be a part of this. Please go to #56 for this issue.
