### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by csf30816** [Newawe/newawe#73]
Is there a server for this yet? I do not think that Heroku is the best for this. If you are aiming for something free I recommend a free server at heliohost.org great quality. I do not work for them just to let you know.

**Comment by haylinmoore** [comment]
I have a server, I have multiple home servers, and a vps 😛

**Comment by csf30816** [comment]
@herohamp Nice. Working on getting a VPS for me.

**Comment by robinp7720** [comment]
A local testing environment is what should be used at this stage of development. You can get a VPS once Newawe is actually production ready. A VPS would be of no use to you apart from being a money drain.

**Comment by haylinmoore** [comment]
^
