### ISSUE TITLE
Country stuff is missing

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe#75]
signupFailPasswordMatch.html - Where is the options in the `<select>` tag
signupFailUsername.html - Where is the options in the `<select>` tag
These are by me:
signupFailUsernameInvalid.html - Where is the options in the `<select>` tag
signupFailEmailInvalid.html - Where is the options in the `<select>` tag
There might be more! Is there something I am missing?

**Comment by joker314** [comment]
I am not saying that 
signup.html
doesn't have them though. Isn't there a js file that generates that field? I thought I saw one.

**Comment by Mrcomputer1** [comment]
There is a script here https://github.com/Newawe/newawe/blob/master/pages/js/register.js but it seems to not be used.

**Comment by joker314** [comment]
How would somebody use the script, as in, how would you "import" it into each file that needs it?

**Comment by joker314** [comment]
Ok, I fixed it manually
