### ISSUE TITLE
Use favicon as logo?

### ISSUE THREAD

**Issue by scratchyone** [Newawe/newawe#85]
In my opinion, the favicon looks better as the logo, and the logo looks better as a favicon. What do you think? I think it looks a lot better on the page.

**Comment by joker314** [comment]
I'm not sure which is which, but the black one does look better as the favicon, and the blue N as the image on the site. I don't know how it is right now.?

**Comment by scratchyone** [comment]
I was thinking the blue N as a favicon. Normally the logo is more detailed than the favicon.

**Comment by joker314** [comment]
Agreed. K, so we need more people to support...

**Comment by scratchyone** [comment]
Just to be clear, I mean 
![screenshot 2016-04-18 at 7 40 21 pm](https://cloud.githubusercontent.com/assets/11479077/14615415/7578d4a8-059d-11e6-85f4-4b1c1858938d.png)

**Comment by joker314** [comment]
That is the best one, out of the two.
However, do we need the second logo? Name a single major website that has a logo with tiny writing in it and a black backdrop. And, to be fair, it looks like a scrabble board piece from the distance, with the $_ being perceived as the value of the piece. Message to creator of logo: It is really good, and think that you might have a career ahead of you, and this logo just doesn't fit the
sizze at which it is being displayed, other than that seems good.

Reminder: No offence to anybody.

**Comment by scratchyone** [comment]
True. If nobody wanted to switch, I think it would like a lot nicer if the
N had a transparent background, and not white

On Monday, April 18, 2016, joker314 <notifications@github.com> wrote:

> That is the best one, out of the two.
> However, do we need the second logo? Name a single major website that has
> a logo with tiny writing in it and a black backdrop. And, to be fair, it
> looks like a scrabble board piece from the distance, with the $_ being
> perceived as the value of the piece. Message to creator of logo: It is
> really good, and think that you might have a career ahead of you, and this
> logo just doesn't fit the
> sizze at which it is being displayed, other than that seems good.
>
> Reminder: No offence to anybody.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Newawe/newawe/issues/85#issuecomment-211537567>
>


--

**Comment by bjskistad** [comment]
I just think we should, get rid of the 'code sharing network' part. I like our current logo. We should change the white nag bar to our teal.

**Comment by bjskistad** [comment]
We shouldn't use the old one as it isn't very explanatory, let's just get rid of code sharing network @DrKat123

**Comment by Radical-from-Scratch** [comment]
You mean get rid of the text right?

**Comment by bjskistad** [comment]
Yeah... the part I mentioned.

**Comment by DrKat123** [comment]
Okay

I might be able to use the PC today

**Comment by DrKat123** [comment]
Well time to make another logo :stuck_out_tongue:

**Comment by DrKat123** [comment]
I have a(n) (crazy and 88% sure that *it will not work*)  idea

**Comment by herohamp** [comment]
Ya I want to see it! I like crazy

**Comment by bjskistad** [comment]
Me too! XD

**Comment by DrKat123** [comment]
Please hold for


8 hours


Till then i'll start making the logo

Now i'm watching TV and i need to work on my math homework

**Comment by DrKat123** [comment]
![logo-1](https://cloud.githubusercontent.com/assets/15071615/14633192/b87623e2-0646-11e6-91b8-c4b6662894ac.png)

**Comment by DrKat123** [comment]
that's just one of 3 of my _crazy_ ideas

**Comment by DrKat123** [comment]
![logo-2](https://cloud.githubusercontent.com/assets/15071615/14634505/68cf437c-064c-11e6-9908-c1e797cbbcf7.png)

**Comment by DrKat123** [comment]
Another logo, but it doesn't use the teal and white colors

**Comment by DrKat123** [comment]
wait
i only have 2 ideas :stuck_out_tongue:

**Comment by DrKat123** [comment]
Now to make it as a favicon


Tomorrow
:stuck_out_tongue:

**Comment by Radical-from-Scratch** [comment]
Those are all nice artwork, but say zero about what Newawe *is*

**Comment by joker314** [comment]
But does google's logo say anything, it is just a G in a font. Same as Yahoo, and facebook, and 'm sure there are more.  
I'm not saying we don't need descriptive text in our logo, just saying that going without is not the end of the world, and might make the logo simpler, and easier to see.

**Comment by Radical-from-Scratch** [comment]
But we are jot as famous asnGoogle.

**Comment by joker314** [comment]
Fair enough. Then can't we just add the 
" Share your code - With the world "
ontop of the logo recently designed

**Comment by herohamp** [comment]
Wow you are good! I have one more Idea I may try! *Insert evil face*

**Comment by herohamp** [comment]
Ok I made a design. The lowercase n represents not following the normal rules and being creative! The Circle represents unlimited possibilities.

http://i.imgur.com/ekW4CFH.png

**Comment by bjskistad** [comment]
I like it!

**Comment by joker314** [comment]
Me too! (won't facebook or twitter sue us, I mean, it is light blue [twitter] and it only contains a white lowercase letter [facebook]...?) But I think it is simple, yet effective. It would be great if we used it. Or we could use everybody's ideas, and combine them? Or have the complex ones on the home page, and the simple ones as the favicon and logo? 'Cus the artwork shouldn't be wasted?

**Comment by herohamp** [comment]
How could they sue us for the icon. I don't think they have a copy right on light blue icons or lowercase white letters?

**Comment by herohamp** [comment]
Or then my new master piece! http://i.imgur.com/IVrXztH.png

**Comment by bjskistad** [comment]
Lemme think of something...

**Comment by DrKat123** [comment]
@Radical-from-Scratch: yes i know
But does Google's icon explains anything?

**Comment by DrKat123** [comment]
![](https://cloud.githubusercontent.com/assets/15071615/14633192/b87623e2-0646-11e6-91b8-c4b6662894ac.png)

**Comment by DrKat123** [comment]
The Julia fractal represents creativity, the gradient behind represents the different shades of programming
The N represents Newawe itself :P

**Comment by DrKat123** [comment]
The Julia Fractal is rotated -45° to represent that "we can break the rules"
:P

**Comment by DrKat123** [comment]
https://cloud.githubusercontent.com/assets/15071615/14634505/68cf437c-064c-11e6-9908-c1e797cbbcf7.png

**Comment by DrKat123** [comment]
that logo is not much different from the first one

**Comment by Jonathan50** [comment]
Lambdaaaaaa

**Comment by DrKat123** [comment]
Okay then

**Comment by Jonathan50** [comment]
fractals can represent recursion.

**Comment by bjskistad** [comment]
To be honest, I don't like the fractals...

**Comment by DrKat123** [comment]
Why?

**Comment by joker314** [comment]
> @Radical-from-Scratch: yes i know
> But does Google's icon explains anything?
I already asked xer, and xe said that google is really big, so when somebody sees a G, they know that it is Google. Her, an n could be anything.

**Comment by DrKat123** [comment]
yeah... :/

**Comment by bjskistad** [comment]
> Why?
It looks to much like your personal logo, and Newawe doesn't have anything to do with fractals. XD

**Comment by herohamp** [comment]
Yea Mine is better xD
It has meaning

**Comment by joker314** [comment]
Yeah. I like your first one better because it isn't going to have copyright issues with Scratch, and it is also a shape of constant width, maximising space wherever we put it

**Comment by joker314** [comment]
> How could they sue us...?

I'm not sure about the US (well, it is mostly international - so it does not matter that much), but you don't copyright things, they are automatically copyrighted from when you create them Facebook has not copyrighted that logo, but the logo is automatically copyrighted.

Not that that is important, because the main part is that if we put a 1x1 light blupixel on their logo, it doesn't become not faceboks, because we just edited a pixle. And then if we change the f to a e, in the same font, does that make it original?

Summary: Fcebook wouldn't dare sue us unti we try and make money off it, because they would otherwise lose money.

**Comment by DrKat123** [comment]
@bjskistad: okay then

**Comment by bjskistad** [comment]
Lol. Srry. XD

**Comment by bjskistad** [comment]
Lol. Srry. XD

**Comment by DrKat123** [comment]
well we'll just have to stick with ![](http://i.imgur.com/IVrXztH.png)

**Comment by bjskistad** [comment]
Kk
