### ISSUE TITLE
Another Error

### ISSUE THREAD

**Issue by herohamp** [Newawe/newawe#89]
http://pastebin.com/exJ4NE4r

**Comment by Jonathan50** [comment]
```js
/^[0-9A-Za-z_-.]+@^[0-9A-Za-z_-.]+(:[0-9]+)?$/
```
should be
```js
/^[0-9A-Za-z_.-]+@[0-9A-Za-z_.-]+(?:[0-9]+)?$/
```

**Comment by joker314** [comment]
Fixed, also added "var" keyword.

**Comment by joker314** [comment]
I mean I made a PR, it still needs to be accepted

**Comment by joker314** [comment]
I made a new PR

**Comment by DrKat123** [comment]
Merged it

**Comment by joker314** [comment]
Thx.
@herohamp when you update the server, could somebody register an account with an invalid email, or an invalid username. It hopefully won't crash the servers. It should give a pink error box. Good night (UK).

**Comment by DrKat123** [comment]
I get an error:
ERR_CONNECTION_REFUSED

**Comment by herohamp** [comment]
I put it back up sorry

**Comment by DrKat123** [comment]
Okay

**Comment by Jonathan50** [comment]
#91 fixes this.
