### ISSUE TITLE
Pages in assets/?

### ISSUE THREAD

**Issue by Jonathan50** [Newawe/newawe#9]
Pages aren't assets...

**Comment by bjskistad** [comment]
Meh. XD

**Comment by bjskistad** [comment]
Should we move it?

**Comment by Jonathan50** [comment]
I think so.

**Comment by herohamp** [comment]
You can I don't feel like spending 20 years trying to do that ten fix any error that come from it

**Comment by Jonathan50** [comment]
If I do, I'll do it on a new branch. BTW we should have tests!

**Comment by Icelys** [comment]
There isn't much to change, so it shouldn't be too hard.

**Comment by Icelys** [comment]
Someone please look over this, I'm worried it might work. While testing it though, it was fine.
