### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by skistaddy** [Newawe/newawe#9]
Should we create a wiki?

**Comment by 109C** [comment]
Do we need a wiki?

**Comment by robinp7720** [comment]
Maybe to document some imporant things in the code and how to setup it up. I think we should atleast create a setup guide once I'm finished with a basic user accounts implementation.

**Comment by skistaddy** [comment]
K.

**Comment by ghost** [comment]
We can create a wiki but should not use Github. The github one is the software wiki. I can include some wiki software in the package.

**Comment by skistaddy** [comment]
Ok!

**Comment by robinp7720** [comment]
@Radical-from-Scratch  @bjskistad  The github wiki is perfect for us. No need for something self hosted
