### ISSUE TITLE
I can register newawe.com

### ISSUE THREAD

**Issue by Dylan5797** [Newawe/newawe#98]
I have enough money in my registar account to buy newawe.com. Does anybody want me to?
or .us but I live in Canada so I'd be reluctant to...

**Comment by DrKat123** [comment]
:P why not?
maybe i can buy newawe.co.id for Indonesian users
:stuck_out_tongue:

**Comment by Jonathan50** [comment]
@DrKat123 I don't see a point of having different domains for different countries...

**Comment by DrKat123** [comment]
Wat

**Comment by Jonathan50** [comment]
> maybe i can buy newawe.co.id **for Indonesian users**

**Comment by DrKat123** [comment]
Google.co.id?

**Comment by Mrcomputer1** [comment]
@DrKat123 Google has some things changed on its other domains (.co.id = Default language changed and maybe closer servers and google doodles for that country, .com.au = maybe closer servers and google doodles for that country)

**Comment by Jonathan50** [comment]
@DrKat123 what do you mean?

**Comment by DrKat123** [comment]
Mrcomputer1:

@DrKat123 Google has some things changed on its other domains (.co.id = Default language changed and maybe closer servers and google doodles for that country, .com.au = maybe closer servers and google doodles for that country)

**Comment by bjskistad** [comment]
1. We would need to get a more expensive plan for more the one domain. 2. I'm the owner, so I *should* get the domain. 3. I don't think we should be getting a domain until we're almost finished with the #v0.5 milestone, which will have profiles and projects.

**Comment by bjskistad** [comment]
What we really need right now is a MySQL Database. If you could get one of those, it would help more at this point. :)

**Comment by Radical-from-Scratch** [comment]
@ Dylan5797 I thought Baran and I agreed to use HG.

@bjskistad 1) No we wouldn't. Do you know what name servers are? 2) Well, I live in a state w/o sales tax so I *might* do the domain. 3) I'm thinking, we'll get the *domain* when we're getting ready to announce its release, but not hosting until just a few days before release. It'll be cheaper and more effective. 5) HostGator comes with MySQL, so we should be all set.

**Comment by bjskistad** [comment]
@Radical-from-Scratch I think that GoDaddy is better for hosting. Do they have MySQL DB.

**Comment by scratchyone** [comment]
Yes. Only $15 a month including a domain name, and 100GB of storage.

**Comment by bjskistad** [comment]
Ok.

**Comment by bjskistad** [comment]
Woops. :P

**Comment by herohamp** [comment]
https://enoi.se is a good host

**Comment by Radical-from-Scratch** [comment]
No, GoDaddy is a bad idea. They were never meant for hosting and have awful support.

**Comment by bjskistad** [comment]
According to reviews, they're very good and are up 99.9% of the time, which is the standard. They also have the cheapest stuff around.

**Comment by Dylan5797** [comment]
HostGator has bad downtimes--don't use it.

**Comment by bjskistad** [comment]
:) That's why we use GoDaddy. :)

**Comment by Radical-from-Scratch** [comment]
I have used both before and GoDaddy is a terrible idea. Also, GoDaddy is quite expensive frankly.

**Comment by Radical-from-Scratch** [comment]
Also, it has a very confusing interface, doesn't let you create multiple FTP accounts, and if there is a name server problem, decides to shout its name everywhere.

**Comment by Radical-from-Scratch** [comment]
*Please*, don't use GoDaddy.

**Comment by herohamp** [comment]
would a digital ocean VPS plus a domain be a better idea?

**Comment by as-com** [comment]
I can provide hosting. According to New Relic, I have very very little downtime and very good performance.

**Comment by bjskistad** [comment]
What do you use?

**Comment by herohamp** [comment]
He uses his own server

**Comment by HittmanA** [comment]
Hey guys sorry I have been gone for awhile. I just bought a new webhoster and domain. I can give us a subdomain as well as hosting for free (from my account). The account has CloudFlare DDoS protection, ClamAV (anti-virus) scanner, automatic weekly backups, unlimited MySQL and Remote MySQL databases/connections, Curl and Ruby on Rails and Perl support (for files), unlimited email accounts, SSL/TLS  Manager, unlimited subdomains, Multiple FTP accounts, URL redirects, custom error page(s) (obviously), cron jobs, instant backups, MIME type manager, Hotline and Leech protection, and more! Let me know if you would like me to set up a subdomain for newawe using my hosting!

**Comment by as-com** [comment]
Does it support Node.js?

**Comment by HittmanA** [comment]
Let me check that...

**Comment by herohamp** [comment]
who did you buy that from?

**Comment by HittmanA** [comment]
hosting24.com

**Comment by HittmanA** [comment]
Question: Is there anyway that newawe could be made without node.js?

**Comment by as-com** [comment]
@HittmanA Hosting24 does not look very trustworthy to me.

**Comment by Radical-from-Scratch** [comment]
While I trust comp09, this is not the kind of project where we would host it ourselves. We had a plan of NC and HG and there is not a good reason to change it. I also agree with not using hosting24

**Comment by Radical-from-Scratch** [comment]
Also, Newawe cannot be on a subdomain. (Yet Scatch is :P )

**Comment by as-com** [comment]
If I host, you can use any domain you want - just create a CNAME to my server and I'll set a virtual host for it.

**Comment by Radical-from-Scratch** [comment]
Comp09, it is really awesome that you are able to self host. That said, I do not think homesting is the right solution unfprtunately.

**Comment by HittmanA** [comment]
hmm ok if you don't want to use my hosting fine. What else could I do?

**Comment by as-com** [comment]
@HittmanA You can still help out with our rewrite: https://github.com/Newawe/newawe/pull/94

**Comment by HittmanA** [comment]
Ok. Also could I take a look at the 404 registration error?

**Comment by Radical-from-Scratch** [comment]
What's the 404 registration error?

**Comment by Radical-from-Scratch** [comment]
Oops, just realized I asked for a response. Re-opening....

**Comment by HittmanA** [comment]
https://github.com/Newawe/newawe/issues/95

**Comment by HittmanA** [comment]
Also how do I install and use npm on a mac?

**Comment by as-com** [comment]
@HittmanA https://nodejs.org/dist/v5.11.0/node-v5.11.0.pkg

**Comment by HittmanA** [comment]
Just run that when it finishes downloading?

**Comment by HittmanA** [comment]
Never mind.

**Comment by masterex1000** [comment]
what about amazon aws?

**Comment by as-com** [comment]
AWS is too expensive.

**Comment by masterex1000** [comment]
what about azure. signup for dream spark and it is free forever. just did it today!

**Comment by Radical-from-Scratch** [comment]
What are you even talking about?

**Comment by herohamp** [comment]
Back to the homehosting thing.  @Radical-from-Scratch Why can't we home host?

**Comment by Radical-from-Scratch** [comment]
The kind of traffic Newawe is likely going to have would probably result in your ISP cancelling your internet service. Also, the entire website will go down if you have a power outage/internet problem/server problem, etc. You also need to worry about disk space, since people will be uploading large files. Also, if you're on vacation or something, then there is NOTHING we can do if someone hacks into Newawe and puts porn on the front page.



But other than that, why not home host? *rolls eyes*

**Comment by as-com** [comment]
I don't think my ISP would mind such traffic. After all, I've been home
hosting my website for quite a while!

We can mitigate the security issue by putting security first. For every
line of code anyone writes, one MUST consider how a malicious actor may
take advantage of that line of code. While we aren't security experts,
careful coding can go a long way.

**Comment by bjskistad** [comment]
We do have a securit tester....

**Comment by bjskistad** [comment]
I think we should let him register it.

**Comment by bjskistad** [comment]
@Dylan5797 Please do register it. We all appreciate it very much. ;)

**Comment by Radical-from-Scratch** [comment]
Whoops, accidentally deleted your message :/

Baran asked dylan to register it, but as previously stated, that isn't a good idea.

I

**Comment by bjskistad** [comment]
@Dylan5797 We would love for you to register newawe.com, if you are still willing. Thank you very much.

**Comment by Radical-from-Scratch** [comment]
Okay, but please don't home-host.

**Comment by Dylan5797** [comment]
Purchased!

**Comment by RonSkons** [comment]
Cool!

**Comment by RonSkons** [comment]
When will the DNS settings be configured?

**Comment by herohamp** [comment]
Ok @Dylan5797 where are we hosting?

**Comment by BKFighter** [comment]
That's cool!

**Comment by herohamp** [comment]
Ok. can you make editor.newawe.com point to our editor?

**Comment by herohamp** [comment]
just put the DNS to 
192.30.252.153
192.30.252.154

**Comment by bjskistad** [comment]
Awesome! @Dylan5797 is there anyway I could get credentials for the site?

**Comment by herohamp** [comment]
@Dylan5797

**Comment by Dylan5797** [comment]
Sorry, I have been gone for the last 3 days. I will create a record for 192.30.252.153 (cool, a 192 IP :stuck_out_tongue_winking_eye:)

**Comment by Jonathan50** [comment]
How are 192 IPs cool...?

**Comment by Radical-from-Scratch** [comment]
@bjskistad Dylan isn't the person to ask for the credentials because dylan is not the *host*, he is the registrar.

**Comment by herohamp** [comment]
We should homehost!

**Comment by herohamp** [comment]
@Dylan5797 No you need to make the subdomain editor point to 192.30.252.153 not the head domain

**Comment by herohamp** [comment]
Bur keep the main domain pointed at 192.30.252.153 because I created a landing page for now

**Comment by bjskistad** [comment]
@Radical-from-Scratch ok, thanks! I will open a new issue for our concerns about hosting.

**Comment by bjskistad** [comment]
#123

**Comment by herohamp** [comment]
@Dylan5797 change the nameservers to 
tara.ns.cloudflare.com

**Comment by bjskistad** [comment]
@Dylan5797 [This](https://newawe.com) doesn't work fyi.

**Comment by Dylan5797** [comment]
I need more details. @herohamp you mean the actual subdomain "editor" point to 192.30.252.153

I would prefer a list formatted like this

A <subdomain> <ip>
CNAME <subdomain> <domain>

**Comment by RonSkons** [comment]
Could we get editor.newawe.com set up? I want to work on the editor.

**Comment by herohamp** [comment]
@dylan just change the name servers

**Comment by Dylan5797** [comment]
My internet is dead, I can't.

**Comment by herohamp** [comment]
You are messaging though ....

**Comment by dylan** [comment]
Wrong @dylan :)

**Comment by herohamp** [comment]
Sorry @dylan

**Comment by Dylan5797** [comment]
rly, i'm messaging from a cell phone

**Comment by herohamp** [comment]
Hohn can you not change name servers from your phone?

**Comment by herohamp** [comment]
Hmmm* not hohn

**Comment by RonSkons** [comment]
Lol AutoCorrect FTW

**Comment by herohamp** [comment]
@Dylan5797 
A editor 192.30.252.153

BUT JUST CHANGE THE NAMESERVERS

**Comment by Radical-from-Scratch** [comment]
You misconfigured GitHub, nothing there....

**Comment by herohamp** [comment]
Where?

**Comment by Dylan5797** [comment]
You need to create a file called CNAME in your GitHub pages root dir of the Github pages repo

**Comment by herohamp** [comment]
I did

**Comment by Radical-from-Scratch** [comment]
Or just put it in a subdirectory, that works too :P

**Comment by herohamp** [comment]
https://github.com/Newawe/AceEditor/blob/gh-pages/CNAME

**Comment by herohamp** [comment]
@Dylan5797 You just need to add the
A editor 192.30.252.153

**Comment by Dylan5797** [comment]
I added the record half an hour ago. :rage:

**Comment by Dylan5797** [comment]
DNS is slow

**Comment by herohamp** [comment]
xD do use all a favor and change the nameservers!

**Comment by Dylan5797** [comment]
kk

**Comment by HittmanA** [comment]
Hi guys! Im back!

**Comment by herohamp** [comment]
Edit you need 2 nameservers
terin.ns.cloudflare.com
tara.ns.cloudflare.com

**Comment by herohamp** [comment]
Sorry I only sent 1

**Comment by HittmanA** [comment]
Anything I should do for newawe now?

**Comment by Radical-from-Scratch** [comment]
We're kinda inactive. Development would be awesome

**Comment by HittmanA** [comment]
Yeah. But what should we / do we need add?

**Comment by RonSkons** [comment]
I mostly work on the editor, but it's down and i'm to lazy to set up on my box 😸 😄

**Comment by Radical-from-Scratch** [comment]
Profile pages

**Comment by Radical-from-Scratch** [comment]
Also, please vote in this poll:

**Comment by Radical-from-Scratch** [comment]
https://www.surveymonkey.com/r/X6LJ9NR

**Comment by herohamp** [comment]
@Dylan5797 did you change the nameservers?

**Comment by Radical-from-Scratch** [comment]
I think he did

**Comment by HittmanA** [comment]
I voted

**Comment by Dylan5797** [comment]
I did but it can take up to 2 days to update.

**Comment by RonSkons** [comment]
Editor is up!

**Comment by herohamp** [comment]
Ok good

**Comment by herohamp** [comment]
The name servers have now been switched!

**Comment by bjskistad** [comment]
Awesome!

**Comment by bjskistad** [comment]
`https://` doesn't work for the website.

**Comment by HittmanA** [comment]
whats the address

**Comment by bjskistad** [comment]
[https://newawe.com](https://newawe.com)

**Comment by RonSkons** [comment]
SSL doesn't work because we don't(?) have SSL.

**Comment by HittmanA** [comment]
Ok what still needs to be added?

**Comment by bjskistad** [comment]
A https redirect.

**Comment by HittmanA** [comment]
No i mean to the website.

**Comment by herohamp** [comment]
It now redirects ;P

**Comment by bjskistad** [comment]
Oh, well, we do need a https redirect, but we also need to add profile pages, connect the editor to the main site, and more.

**Comment by bjskistad** [comment]
Awesome!

**Comment by HittmanA** [comment]
Ill try to connect the editor to the main site. What page should it be on?

**Comment by RonSkons** [comment]
https://wp-mix.com/htaccess-redirect-http-to-https/

**Comment by herohamp** [comment]
I know how to connect to main site!

**Comment by herohamp** [comment]
first we need a DB

**Comment by herohamp** [comment]
then just send them to the editor with post data saying all the code. Then have javascript place the code into the editor!

**Comment by herohamp** [comment]
Easy!

**Comment by HittmanA** [comment]
That could be laggy right?

**Comment by RonSkons** [comment]
Only with lots of code

**Comment by HittmanA** [comment]
Yeah but many people will have lots of code

**Comment by bjskistad** [comment]
Just need a loading screen then. My online editor takes a bit to load.

Note: We haven't really talked about this, but idk if we will be supplying a terminal or not.

**Comment by herohamp** [comment]
nope! We are not a IDE

**Comment by RonSkons** [comment]
Can we close the issue and move to Gitter?

**Comment by herohamp** [comment]
yup

**Comment by bjskistad** [comment]
K.

**Comment by Jonathan50** [comment]
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```
we should use HTML5

**Comment by herohamp** [comment]
http://blog.newawe.com/

**Comment by HittmanA** [comment]
Could I be allowed to post new blog updates for newawe?

**Comment by Dylan5797** [comment]
Me too

**Comment by herohamp** [comment]
Yeah DM on gitter of info!
