### ISSUE TITLE
May I have the error log (for the server crashing)

### ISSUE THREAD

**Issue by joker314** [Newawe/newawe#99]
I just crashed Newawe again, may I have the error log please. Sorry about crashing it, but we need to find all bugs before publication

**Comment by joker314** [comment]
Why I put priority high: Because nobody can register unless this is fixed
Why I assigned @herohamp : because he runs the server

**Comment by bjskistad** [comment]
Kk

**Comment by herohamp** [comment]
Joker I will give you vnc access for now. DON'T MESS WITH ANYTHING BUT THE LOGS! and the server.

**Comment by herohamp** [comment]
Joke I will give your VNC acess for now! Don't mess anything up. Just put an email for me to send the info.

**Comment by joker314** [comment]
m a x z u b a 2 2 ( a t ) y a h o o . c o . u k
(Remove excess spaces and replace "(at)" with th @ symbol)
Tell me when you have copied it down so that I can edit it out

**Comment by joker314** [comment]
But can't you just post the most recent log here? I just need the last bit where it gives an error message

**Comment by joker314** [comment]
I am really struggling with the VNC (haven't managed to connect because of an error in the software I am using). Would it be possible to have the latest error logs posted here?

**Comment by herohamp** [comment]
`
someone attempted to sign up with the but they did not fill in a field in the form
/home/pi/Desktop/newawe-node/server.js:83
    return substitute(readFile("pages/global.html"),{"content": substitute(readFile("pages/html/" + config.pages[pageName].file), {"page-title": config.pages[pageName].title, "site-title": config.pages[pageName].siteTitle})});
                                                                                                                          ^
 
TypeError: Cannot read property 'file' of undefined
    at globalSiteText (/home/pi/Desktop/newawe-node/server.js:83:120)
    at register (/home/pi/Desktop/newawe-node/server.js:219:22)
    at /home/pi/Desktop/newawe-node/server.js:277:5
    at IncomingMessage.<anonymous> (/home/pi/Desktop/newawe-node/server.js:240:34)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

`

**Comment by joker314** [comment]
Thanks. #100 got merged, but #101 should be the one that fixes the bug. Shouldn't we try catching excepions, because it is otherwise quite dangerous?

**Comment by bjskistad** [comment]
Merged #101

**Comment by herohamp** [comment]
Ok will update when I have time

**Comment by joker314** [comment]
Great.
